In [1]:
%pip uninstall --yes 'keras' 'matplotlib' 'scikit-learn' 'tensorflow'

Found existing installation: keras 3.10.0
Uninstalling keras-3.10.0:
  Successfully uninstalled keras-3.10.0
Found existing installation: matplotlib 3.10.0
Uninstalling matplotlib-3.10.0:
  Successfully uninstalled matplotlib-3.10.0
Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Found existing installation: tensorflow 2.19.0
Uninstalling tensorflow-2.19.0:
  Successfully uninstalled tensorflow-2.19.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import warnings
warnings.simplefilter('ignore')

In [3]:
import os
import sys
import subprocess

In [4]:
def set_env(input_archive, temp_dir):

    if not os.path.exists(temp_dir):
        os.makedirs(temp_dir, exist_ok=True)
        
        subprocess.run(['tar', '-xzf', input_archive, '-C', temp_dir], check=True)
    
    subprocess.run([
        sys.executable, 
        '-m', 
        'pip', 
        'install', 
        '--no-index', 
        '--find-links', 
        f'{temp_dir}/wheels', 
        'unsloth', 
        'trl', 
        'vllm', 
        'openai_harmony'
    ], check=True)

In [5]:
set_env(
    input_archive='/kaggle/input/aimo-3-utils/wheels.tar.gz', 
    temp_dir='/kaggle/tmp/setup'
)

Looking in links: /kaggle/tmp/setup/wheels
Processing /kaggle/tmp/setup/wheels/unsloth-2025.12.9-py3-none-any.whl
Processing /kaggle/tmp/setup/wheels/trl-0.24.0-py3-none-any.whl
Processing /kaggle/tmp/setup/wheels/vllm-0.11.2-cp38-abi3-manylinux1_x86_64.whl
Processing /kaggle/tmp/setup/wheels/openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing /kaggle/tmp/setup/wheels/unsloth_zoo-2025.12.7-py3-none-any.whl (from unsloth)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.45.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth) (25.0)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.8.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.23.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Processing /kaggle/tmp/setup/wheels/tyro-1.0.3-py3-none-any.whl (from unsloth)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Processing /kaggle/tmp/setup/wheels/xformers-0.0.33.post1-cp39-abi3-manylinux_2_28_x86_64.whl (from unsloth)
Processing /kaggle/tmp/setup/wheels/bitsandbytes-0.49.0-py3-none-manylinux_2_24_x86_64.whl (from unsloth)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.4.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Processing /kaggle/tmp/setup/wheels/datasets-4.3.0-py3-none-any.whl (from unsloth)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.11.0)
Requirement already satisfied: peft!=0.11.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.17.1)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.35.2)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,<=4.57.3,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.57.1)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm) (2025.11.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (5.5.2)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.5)
Requirement already satisfied: blake3 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.0.8)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.1)
Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.119.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.2)
Requirement already satisfied: openai>=1.99.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.109.1)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.12.5)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.23.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm) (11.3.0)
Processing /kaggle/tmp/setup/wheels/prometheus_fastapi_instrumentator-7.1.0-py3-none-any.whl (from vllm)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.12.0)
Processing /kaggle/tmp/setup/wheels/lm_format_enforcer-0.11.3-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/llguidance-1.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/outlines_core-0.2.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/diskcache-5.6.3-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/lark-1.2.2-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/xgrammar-0.1.25-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.15.0)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.20.1)
Processing /kaggle/tmp/setup/wheels/partial_json_parser-0.2.1.1.post7-py3-none-any.whl (from vllm)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Processing /kaggle/tmp/setup/wheels/msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/gguf-0.17.1-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/mistral_common-1.8.8-py3-none-any.whl (from mistral_common[image]>=1.8.5->vllm)
Requirement already satisfied: opencv-python-headless>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.12.0.88)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm) (6.0.3)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Processing /kaggle/tmp/setup/wheels/setuptools-80.9.0-py3-none-any.whl (from vllm)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.1)
Processing /kaggle/tmp/setup/wheels/compressed_tensors-0.12.2-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/depyf-0.20.0-py3-none-any.whl (from vllm)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.1)
Processing /kaggle/tmp/setup/wheels/watchfiles-1.1.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.0.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from vllm) (1.15.3)
Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from vllm) (1.13.0)
Processing /kaggle/tmp/setup/wheels/pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/cbor2-5.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/anthropic-0.71.0-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/model_hosting_container_standards-0.1.12-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/numba-0.61.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from vllm)
Requirement already satisfied: ray>=2.48.0 in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (2.52.1)
Processing /kaggle/tmp/setup/wheels/torch-2.9.0+cu128-cp312-cp312-manylinux_2_28_x86_64.whl (from unsloth)
Processing /kaggle/tmp/setup/wheels/torchaudio-2.9.0+cu128-cp312-cp312-manylinux_2_28_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/torchvision-0.24.0+cu128-cp312-cp312-manylinux_2_28_x86_64.whl (from unsloth)
Processing /kaggle/tmp/setup/wheels/flashinfer_python-0.5.2-py3-none-any.whl (from vllm)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (4.12.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.11.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (1.3.1)
Processing /kaggle/tmp/setup/wheels/loguru-0.7.3-py3-none-any.whl (from compressed-tensors==0.12.2->vllm)
Processing /kaggle/tmp/setup/wheels/astor-0.8.1-py2.py3-none-any.whl (from depyf==0.20.0->vllm)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.4.0)
Processing /kaggle/tmp/setup/wheels/apache_tvm_ffi-0.1.7-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (from flashinfer-python==0.5.2->vllm)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (8.3.1)
Processing /kaggle/tmp/setup/wheels/nvidia_cudnn_frontend-1.17.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (from flashinfer-python==0.5.2->vllm)
Processing /kaggle/tmp/setup/wheels/nvidia_cutlass_dsl-4.3.4-cp312-cp312-manylinux_2_28_x86_64.whl (from flashinfer-python==0.5.2->vllm)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (12.575.51)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (0.9.0)
Processing /kaggle/tmp/setup/wheels/interegular-0.3.3-py37-none-any.whl (from lm-format-enforcer==0.11.3->vllm)
Processing /kaggle/tmp/setup/wheels/llvmlite-0.44.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from numba==0.61.2->vllm)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2025.10.0)
Processing /kaggle/tmp/setup/wheels/nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Processing /kaggle/tmp/setup/wheels/nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Processing /kaggle/tmp/setup/wheels/nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/triton-3.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (from unsloth)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.6.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (22.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Processing /kaggle/tmp/setup/wheels/multiprocess-0.70.16-py312-none-any.whl (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
Processing /kaggle/tmp/setup/wheels/fsspec-2025.9.0-py3-none-any.whl (from torch>=2.4.0->unsloth)
Requirement already satisfied: starlette<0.49.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.48.0)
Processing /kaggle/tmp/setup/wheels/fastapi_cli-0.0.20-py3-none-any.whl (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.0.20)
Requirement already satisfied: email-validator>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.3.0)
Requirement already satisfied: uvicorn>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.38.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.2.1rc0)
Requirement already satisfied: jsonschema>=4.21.1 in /usr/local/lib/python3.12/dist-packages (from mistral_common>=1.8.5->mistral_common[image]>=1.8.5->vllm) (4.25.1)
Processing /kaggle/tmp/setup/wheels/pydantic_extra_types-2.10.6-py3-none-any.whl (from pydantic-extra-types[pycountry]>=2.10.5->mistral_common>=1.8.5->mistral_common[image]>=1.8.5->vllm)
Requirement already satisfied: jmespath in /usr/local/lib/python3.12/dist-packages (from model-hosting-container-standards<1.0.0->vllm) (1.0.1)
INFO: pip is looking at multiple versions of model-hosting-container-standards to determine which version is compatible with other requirements. This could take a while.
Processing /kaggle/tmp/setup/wheels/fastapi-0.128.0-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/annotated_doc-0.0.4-py3-none-any.whl (from fastapi[standard]>=0.115.0->vllm)
Requirement already satisfied: pydantic-settings>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.11.0)
Processing /kaggle/tmp/setup/wheels/starlette-0.50.0-py3-none-any.whl (from fastapi[standard]>=0.115.0->vllm)
Processing /kaggle/tmp/setup/wheels/supervisor-4.3.0-py2.py3-none-any.whl (from model-hosting-container-standards<1.0.0->vllm)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.4.2)
INFO: pip is looking at multiple versions of ray to determine which version is compatible with other requirements. This could take a while.
Processing /kaggle/tmp/setup/wheels/ray-2.53.0-cp312-cp312-manylinux2014_x86_64.whl (from ray[cgraph]>=2.48.0->vllm)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.48.0->ray[cgraph]>=2.48.0->vllm) (1.1.2)
INFO: pip is looking at multiple versions of ray[cgraph] to determine which version is compatible with other requirements. This could take a while.
Requirement already satisfied: cupy-cuda12x in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (13.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2025.11.12)
Processing /kaggle/tmp/setup/wheels/torchao-0.15.0+cu128-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (from unsloth_zoo>=2025.12.7->unsloth)
Processing /kaggle/tmp/setup/wheels/cut_cross_entropy-25.1.1-py3-none-any.whl (from unsloth_zoo>=2025.12.7->unsloth)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.22.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from email-validator>=2.0.0->fastapi[standard]>=0.115.0->vllm) (2.8.0)
Requirement already satisfied: typer>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.20.0)
Processing /kaggle/tmp/setup/wheels/rich_toolkit-0.17.1-py3-none-any.whl (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
Processing /kaggle/tmp/setup/wheels/fastapi_cloud_cli-0.8.0-py3-none-any.whl (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kauldron 1.3.0 requires scikit-learn, which is not installed.
kauldron 1.3.0 requires tensorflow, which is not installed.
ydata-profiling 4.18.0 requires matplotlib<=3.10,>=3.5, which is not installed.
pyldavis 3.4.1 requires scikit-learn>=1.0.0, which is not installed.
stable-baselines3 2.1.0 requires matplotlib, which is not installed.
sentence-transformers 5.1.1 requires scikit-learn, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
cuml-cu12 25.6.0 requires scikit-learn>=1.5, which is not installed.
bigframes 2.26.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
bigframes 2.26.0 requires matplotlib>=3.7.1, which is not installed.
arviz 0.22.0 requires matplotlib>=3.8, which is not installed.
pynndescent 0.5.13 requires scikit-learn>=0.18, which is not installed.
shap 0.49.1 requires scikit-learn, which is not installed.
fastai 2.8.4 requires matplotlib, which is not installed.
fastai 2.8.4 requires scikit-learn, which is not installed.
umap-learn 0.5.9.post2 requires scikit-learn>=1.6, which is not installed.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.2.19 which is incompatible.
cudf-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
cudf-cu12 25.6.0 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 22.0.0 which is incompatible.
gradio 5.49.1 requires pydantic<2.12,>=2.0, but you have pydantic 2.12.5 which is incompatible.
cuml-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
bigframes 2.26.0 requires rich<14,>=12.4.4, but you have rich 14.2.0 which is incompatible.
pylibraft-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
cuvs-cu12 25.6.1 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
fastai 2.8.4 requires torch<2.9,>=1.10, but you have torch 2.9.0+cu128 which is incompatible.
rmm-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
pylibcudf-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
pylibcudf-cu12 25.6.0 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 22.0.0 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2025.9.0 which is incompatible.

In [6]:
subprocess.run(['ls', '/kaggle/tmp/setup/tiktoken_encodings'])

cl100k_base.tiktoken
o200k_base.tiktoken

CompletedProcess(args=['ls', '/kaggle/tmp/setup/tiktoken_encodings'], returncode=0)

In [7]:
os.environ['TRANSFORMERS_NO_TF'] = '1'
os.environ['TRANSFORMERS_NO_FLAX'] = '1'
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
os.environ['TOKENIZERS_PARALLELISM'] = 'false'
os.environ['TRITON_PTXAS_PATH'] = '/usr/local/cuda/bin/ptxas'
os.environ['TIKTOKEN_ENCODINGS_BASE'] = '/kaggle/tmp/setup/tiktoken_encodings'

In [8]:
import gc
import re
import math
import time
import queue
import threading
import contextlib
from typing import Optional
from jupyter_client import KernelManager
from collections import Counter, defaultdict
from concurrent.futures import as_completed, ThreadPoolExecutor

import pandas as pd
import polars as pl

from openai import OpenAI

from openai_harmony import (
    HarmonyEncodingName, 
    load_harmony_encoding, 
    SystemContent, 
    ReasoningEffort, 
    ToolNamespaceConfig, 
    Author, 
    Message, 
    Role, 
    TextContent, 
    Conversation
)

from transformers import set_seed
import kaggle_evaluation.aimo_3_inference_server

In [9]:
class CFG:
    
    system_prompt = (
        'You are an elite mathematical problem solver with expertise at the International '
        'Mathematical Olympiad (IMO) level. Your goal is to find the correct answer through '
        'rigorous mathematical reasoning.\n\n'
        
        '# Problem-Solving Approach:\n'
        '1. UNDERSTAND: Carefully read and rephrase the problem in your own words. '
        'Identify what is given, what needs to be found, and any constraints.\n'
        '2. EXPLORE: Consider multiple solution strategies. Think about relevant theorems, '
        'techniques, patterns, or analogous problems. Don\'t commit to one approach immediately.\n'
        '3. PLAN: Select the most promising approach and outline key steps before executing.\n'
        '4. EXECUTE: Work through your solution methodically. Show all reasoning steps clearly.\n'
        '5. VERIFY: Check your answer by substituting back, testing edge cases, or using '
        'alternative methods. Ensure logical consistency throughout.\n\n'
        
        '# Mathematical Reasoning Principles:\n'
        '- Break complex problems into smaller, manageable sub-problems\n'
        '- Look for patterns, symmetries, and special cases that provide insight\n'
        '- Use concrete examples to build intuition before generalizing\n'
        '- Consider extreme cases and boundary conditions\n'
        '- If stuck, try working backwards from the desired result\n'
        '- Be willing to restart with a different approach if needed\n\n'
        
        '# Verification Requirements:\n'
        '- Cross-check arithmetic and algebraic manipulations\n'
        '- Verify that your solution satisfies all problem constraints\n'
        '- Test your answer with simple cases or special values when possible\n'
        '- Ensure dimensional consistency and reasonableness of the result\n\n'
        
        '# Output Format:\n'
        'The final answer must be a non-negative integer between 0 and 99999.\n'
        'Place your final numerical answer inside \\boxed{}, e.g., \\boxed{42}\n\n'
        
        'Think step-by-step and show your complete reasoning process. Quality of reasoning '
        'is as important as the final answer.'
    )
    
    tool_prompt = (
        'Use this tool to execute Python code for:\n'
        '- Complex calculations that would be error-prone by hand\n'
        '- Numerical verification of analytical results\n'
        '- Generating examples or testing conjectures\n'
        '- Visualizing problem structure when helpful\n'
        '- Brute-force verification for small cases\n\n'
        
        'The environment is a stateful Jupyter notebook. Code persists between executions.\n'
        'Always use print() to display results. Write clear, well-commented code.\n\n'
        
        'Remember: Code should support your mathematical reasoning, not replace it. '
        'Explain what you\'re computing and why before running code.'
    )
    
    preference_prompt = (
        'You have access to `math`, `numpy`, and `sympy` for:\n\n'
        
        '# Symbolic Computation (sympy):\n'
        '- Algebraic manipulation and simplification\n'
        '- Solving equations and systems of equations\n'
        '- Symbolic differentiation and integration\n'
        '- Number theory functions (primes, divisors, modular arithmetic)\n'
        '- Polynomial operations and factorization\n'
        '- Working with mathematical expressions symbolically\n\n'
        
        '# Numerical Computation (numpy):\n'
        '- Array operations and linear algebra\n'
        '- Efficient numerical calculations for large datasets\n'
        '- Matrix operations and eigenvalue problems\n'
        '- Statistical computations\n\n'
        
        '# Mathematical Functions (math):\n'
        '- Standard mathematical functions (trig, log, exp)\n'
        '- Constants like pi and e\n'
        '- Basic operations for single values\n\n'
        
        'Best Practices:\n'
        '- Use sympy for exact symbolic answers when possible\n'
        '- Use numpy for numerical verification and large-scale computation\n'
        '- Combine symbolic and numerical approaches: derive symbolically, verify numerically\n'
        '- Document your computational strategy clearly\n'
        '- Validate computational results against known cases or theoretical bounds'
    )
    
    served_model_name = 'gpt-oss'
    model_path = '/kaggle/input/gpt-oss-120b/transformers/default/1'
    
    kv_cache_dtype = 'fp8_e4m3'
    dtype = 'auto'

    high_problem_timeout = 900
    base_problem_timeout = 300

    notebook_limit = 17400
    server_timeout = 180

    session_timeout = 960
    jupyter_timeout = 6
    sandbox_timeout = 3

    stream_interval = 200
    context_tokens = 65536
    buffer_tokens = 512
    search_tokens = 32
    top_logprobs = 5
    batch_size = 256
    early_stop = 4
    attempts = 8
    workers = 16
    turns = 128
    seed = 42

    gpu_memory_utilization = 0.96
    temperature = 1.0
    min_p = 0.02

In [10]:
set_seed(CFG.seed)

In [11]:
class AIMO3Template:

    def __init__(self):

        pass

    def get_system_content(self, system_prompt: str, tool_config: ToolNamespaceConfig) -> SystemContent:

        return (
            SystemContent.new()
            .with_model_identity(system_prompt)
            .with_reasoning_effort(reasoning_effort=ReasoningEffort.HIGH)
            .with_tools(tool_config)
        )

    def apply_chat_template(
        self, 
        system_prompt: str, 
        user_prompt: str, 
        tool_config: ToolNamespaceConfig
    ) -> list[Message]:

        system_content = self.get_system_content(system_prompt, tool_config)        
        system_message = Message.from_role_and_content(Role.SYSTEM, system_content)

        user_message = Message.from_role_and_content(Role.USER, user_prompt)

        return [system_message, user_message]

In [12]:
class AIMO3Sandbox:

    sys.set_int_max_str_digits(0)
    _port_lock = threading.Lock()
    _next_port = 50000

    @classmethod
    def _get_next_ports(cls, count: int = 5) -> list[int]:

        with cls._port_lock:
            ports = list(range(cls._next_port, cls._next_port + count))
            cls._next_port += count

            return ports

    def __init__(self, timeout: float):

        self._default_timeout = timeout
        self._owns_kernel = False
        self._client = None
        self._km = None
        
        ports = self._get_next_ports(5)

        env = os.environ.copy()
        env['PYDEVD_DISABLE_FILE_VALIDATION'] = '1'
        env['PYDEVD_WARN_EVALUATION_TIMEOUT'] = '0'
        env['JUPYTER_PLATFORM_DIRS'] = '1'
        env['PYTHONWARNINGS'] = 'ignore'
        env['MPLBACKEND'] = 'Agg'

        self._km = KernelManager()
        self._km.shell_port = ports[0]
        self._km.iopub_port = ports[1]
        self._km.stdin_port = ports[2]
        self._km.hb_port = ports[3]
        self._km.control_port = ports[4]

        self._km.start_kernel(env=env, extra_arguments=['--Application.log_level=CRITICAL'])

        self._client = self._km.blocking_client()
        self._client.start_channels()
        self._client.wait_for_ready(timeout=self._default_timeout)
        self._owns_kernel = True

        self.execute(
            'import math\n'
            'import numpy\n'
            'import sympy\n'
            'import itertools\n'
            'import collections\n'
            'import mpmath\n'
            'mpmath.mp.dps = 64\n'
        )

    def _format_error(self, traceback: list[str]) -> str:

        clean_lines = []

        for frame in traceback:
            clean_frame = re.sub(r'\x1b\[[0-9;]*m', '', frame)

            if 'File "' in clean_frame and 'ipython-input' not in clean_frame:
                continue

            clean_lines.append(clean_frame)

        return ''.join(clean_lines)

    def execute(self, code: str, timeout: float | None = None) -> str:

        client = self._client
        effective_timeout = timeout or self._default_timeout
        
        msg_id = client.execute(
            code, 
            store_history=True, 
            allow_stdin=False, 
            stop_on_error=False
        )

        stdout_parts = []
        stderr_parts = []
        
        start_time = time.time()

        while True:
            elapsed = time.time() - start_time

            if elapsed > effective_timeout:
                self._km.interrupt_kernel()

                return f'[ERROR] Execution timed out after {effective_timeout} seconds'

            try:
                msg = client.get_iopub_msg(timeout=1.0)

            except queue.Empty:
                continue

            if msg.get('parent_header', {}).get('msg_id') != msg_id:
                continue

            msg_type = msg.get('msg_type')
            content = msg.get('content', {})

            if msg_type == 'stream':
                text = content.get('text', '')

                if content.get('name') == 'stdout':
                    stdout_parts.append(text)

                else:
                    stderr_parts.append(text)

            elif msg_type == 'error':
                traceback_list = content.get('traceback', [])

                stderr_parts.append(self._format_error(traceback_list))

            elif msg_type in {'execute_result', 'display_data'}:
                data = content.get('data', {})
                text = data.get('text/plain')

                if text:
                    stdout_parts.append(text if text.endswith('\n') else f'{text}\n')

            elif msg_type == 'status':
                if content.get('execution_state') == 'idle':
                    break

        stdout = ''.join(stdout_parts)
        stderr = ''.join(stderr_parts)

        if stderr:
            return f'{stdout.rstrip()}\n{stderr}' if stdout else stderr

        return stdout if stdout.strip() else '[WARN] No output. Use print() to see results.'

    def close(self):

        with contextlib.suppress(Exception):
            if self._client:
                self._client.stop_channels()

        if self._owns_kernel and self._km is not None:
            with contextlib.suppress(Exception):
                self._km.shutdown_kernel(now=True)

            with contextlib.suppress(Exception):
                self._km.cleanup_resources()

    def reset(self):
        
        self.execute(
            '%reset -f\n'
            'import sys\n'
            'sys.set_int_max_str_digits(0)\n'
            'sys.setrecursionlimit(20000)\n'
            'import math\n'
            'import numpy\n'
            'import sympy\n'
            'import itertools\n'
            'import collections\n'
            'import mpmath\n'
            'mpmath.mp.dps = 64\n'
        )

    def __del__(self):

        self.close()

In [13]:
class AIMO3Tool:

    def __init__(self, local_jupyter_timeout: float, tool_prompt: str, sandbox=None):

        self._local_jupyter_timeout = local_jupyter_timeout
        self._tool_prompt = tool_prompt
        self._jupyter_session = sandbox
        
        self._owns_session = sandbox is None
        
        self._execution_lock = threading.Lock()
        self._init_lock = threading.Lock()

    def _ensure_session(self):

        if self._jupyter_session is None:
            with self._init_lock:
                if self._jupyter_session is None:
                    self._jupyter_session = AIMO3Sandbox(timeout=self._local_jupyter_timeout)

    def _ensure_last_print(self, code: str) -> str:

        lines = code.strip().split('\n')

        if not lines:
            return code

        last_line = lines[-1].strip()

        if 'print' in last_line or 'import' in last_line:
            return code

        if not last_line:
            return code

        if last_line.startswith('#'):
            return code

        lines[-1] = 'print(' + last_line + ')'

        return '\n'.join(lines)

    @property
    def instruction(self) -> str:

        return self._tool_prompt

    @property
    def tool_config(self) -> ToolNamespaceConfig:

        return ToolNamespaceConfig(
            name='python', 
            description=self.instruction, 
            tools=[]
        )

    def _make_response(self, output: str, channel: str | None = None) -> Message:

        content = TextContent(text=output)
        author = Author(role=Role.TOOL, name='python')
        message = Message(author=author, content=[content]).with_recipient('assistant')

        if channel:
            message = message.with_channel(channel)

        return message

    def process_sync_plus(self, message: Message) -> list[Message]:

        self._ensure_session()
        raw_script = message.content[0].text
        final_script = raw_script #self._ensure_last_print(raw_script)

        with self._execution_lock:
            try:
                output = self._jupyter_session.execute(final_script)

            except TimeoutError as exc:
                output = f'[ERROR] {exc}'

        return [self._make_response(output, channel=message.channel)]

In [14]:
class AIMO3Solver:

    def __init__(self, cfg, port: int = 8000):
    
        self.cfg = cfg
        self.port = port
        self.base_url = f'http://0.0.0.0:{port}/v1'
        self.api_key = 'sk-local'
        self.template = AIMO3Template()
        self.encoding = load_harmony_encoding(HarmonyEncodingName.HARMONY_GPT_OSS)
        self.stop_token_ids = self.encoding.stop_tokens_for_assistant_actions()
    
        self._preload_model_weights()
        
        self.server_process = self._start_server()
    
        self.client = OpenAI(
            base_url=self.base_url, 
            api_key=self.api_key, 
            timeout=self.cfg.session_timeout
        )
    
        self._wait_for_server()
        self._initialize_kernels()
    
        self.notebook_start_time = time.time()
        self.problems_remaining = 50
    
    def _preload_model_weights(self) -> None:
    
        print(f'Loading model weights from {self.cfg.model_path} into OS Page Cache...')
        start_time = time.time()
        
        files_to_load = []
        total_size = 0
    
        for root, _, files in os.walk(self.cfg.model_path):
            for file_name in files:
                file_path = os.path.join(root, file_name)
    
                if os.path.isfile(file_path):
                    files_to_load.append(file_path)
                    total_size += os.path.getsize(file_path)
    
        def _read_file(path: str) -> None:
    
            with open(path, 'rb') as file_object:
                while file_object.read(1024 * 1024 * 1024):
                    pass
    
        with ThreadPoolExecutor(max_workers=self.cfg.workers) as executor:
            list(executor.map(_read_file, files_to_load))
    
        elapsed = time.time() - start_time
        print(f'Processed {len(files_to_load)} files ({total_size / 1e9:.2f} GB) in {elapsed:.2f} seconds.\n')
    
    def _start_server(self) -> subprocess.Popen:
    
        cmd = [
            sys.executable, 
            '-m', 
            'vllm.entrypoints.openai.api_server', 
            '--seed', 
            str(self.cfg.seed), 
            '--model', 
            self.cfg.model_path, 
            '--served-model-name', 
            self.cfg.served_model_name, 
            '--tensor-parallel-size', 
            '1', 
            '--max-num-seqs', 
            str(self.cfg.batch_size), 
            '--gpu-memory-utilization', 
            str(self.cfg.gpu_memory_utilization), 
            '--host', 
            '0.0.0.0', 
            '--port', 
            str(self.port), 
            '--dtype', 
            self.cfg.dtype, 
            '--kv-cache-dtype', 
            self.cfg.kv_cache_dtype, 
            '--max-model-len', 
            str(self.cfg.context_tokens), 
            '--stream-interval', 
            str(self.cfg.stream_interval), 
            '--async-scheduling', 
            '--disable-log-stats', 
            '--enable-prefix-caching'
        ]
    
        self.log_file = open('vllm_server.log', 'w')
    
        return subprocess.Popen(
            cmd, 
            stdout=self.log_file, 
            stderr=subprocess.STDOUT, 
            start_new_session=True
        )
    
    def _wait_for_server(self):
    
        print('Waiting for vLLM server...')
        start_time = time.time()
    
        for _ in range(self.cfg.server_timeout):
            return_code = self.server_process.poll()
    
            if return_code is not None:
                self.log_file.flush()
    
                with open('vllm_server.log', 'r') as log_file:
                    logs = log_file.read()
    
                raise RuntimeError(f'Server died with code {return_code}. Full logs:\n{logs}\n')
    
            try:
                self.client.models.list()
                elapsed = time.time() - start_time
                print(f'Server is ready (took {elapsed:.2f} seconds).\n')
    
                return
    
            except Exception:
                time.sleep(1)
    
        raise RuntimeError('Server failed to start (timeout).\n')
    
    def _initialize_kernels(self) -> None:
    
        print(f'Initializing {self.cfg.workers} persistent Jupyter kernels...')
        start_time = time.time()
    
        self.sandbox_pool = queue.Queue()
    
        def _create_sandbox():
            
            return AIMO3Sandbox(timeout=self.cfg.jupyter_timeout)
    
        with ThreadPoolExecutor(max_workers=self.cfg.workers) as executor:
            futures = [executor.submit(_create_sandbox) for _ in range(self.cfg.workers)]
    
            for future in as_completed(futures):
                self.sandbox_pool.put(future.result())
    
        elapsed = time.time() - start_time
        print(f'Kernels initialized in {elapsed:.2f} seconds.\n')
    
    def _scan_for_answer(self, text: str) -> int | None:
        
        pattern = r'\\boxed\s*\{\s*([0-9,]+)\s*\}'
        matches = re.findall(pattern, text)
    
        if matches:
            try:
                clean_value = matches[-1].replace(',', '')
                value = int(clean_value)
    
                if 0 <= value <= 99999:
                    return value
    
            except ValueError:
                pass
                
        pattern = r'final\s+answer\s+is\s*([0-9,]+)'
        matches = re.findall(pattern, text, re.IGNORECASE)
    
        if matches:
            try:
                clean_value = matches[-1].replace(',', '')
                value = int(clean_value)
    
                if 0 <= value <= 99999:
                    return value
    
            except ValueError:
                pass
    
        return None
    
    def _compute_mean_entropy(self, logprobs_buffer: list) -> float:
    
        if not logprobs_buffer:
            return float('inf')
    
        total_entropy = 0.0
        token_count = 0
    
        for top_logprobs_dict in logprobs_buffer:
            
            if not isinstance(top_logprobs_dict, dict):
                continue
            
            if not top_logprobs_dict:
                continue
            
            token_entropy = 0.0
            
            for token_str, log_prob in top_logprobs_dict.items():
                prob = math.exp(log_prob)
                
                if prob > 0:
                    token_entropy -= prob * math.log2(prob)
            
            total_entropy += token_entropy
            token_count += 1
    
        if token_count == 0:
            return float('inf')
    
        return total_entropy / token_count
    
    def _process_attempt(
        self, 
        problem: str, 
        system_prompt: str, 
        attempt_index: int, 
        stop_event: threading.Event, 
        deadline: float
    ) -> dict:
    
        if stop_event.is_set() or time.time() > deadline:
            return {
                'Attempt': attempt_index + 1, 
                'Answer': None, 
                'Python Calls': 0, 
                'Python Errors': 0, 
                'Response Length': 0, 
                'Entropy': float('inf')
            }
    
        local_tool = None
        sandbox = None
        python_calls = 0
        python_errors = 0
        total_tokens = 0
        final_answer = None
        
        logprobs_buffer = []
    
        attempt_seed = int(math.pow(self.cfg.seed + attempt_index, 2))
    
        try:
            sandbox = self.sandbox_pool.get(timeout=self.cfg.sandbox_timeout)
    
            local_tool = AIMO3Tool(
                local_jupyter_timeout=self.cfg.jupyter_timeout, 
                tool_prompt=self.cfg.tool_prompt, 
                sandbox=sandbox
            )
    
            encoding = self.encoding
            messages = self.template.apply_chat_template(
                system_prompt, 
                problem, 
                local_tool.tool_config
            )
    
            conversation = Conversation.from_messages(messages)
    
            for _ in range(self.cfg.turns):
                if stop_event.is_set() or time.time() > deadline:
                    break
    
                prompt_ids = encoding.render_conversation_for_completion(conversation, Role.ASSISTANT)
                max_tokens = self.cfg.context_tokens - len(prompt_ids)
    
                if max_tokens < self.cfg.buffer_tokens:
                    break
    
                stream = self.client.completions.create(
                    model=self.cfg.served_model_name, 
                    temperature=self.cfg.temperature, 
                    logprobs=self.cfg.top_logprobs, 
                    max_tokens=max_tokens, 
                    prompt=prompt_ids, 
                    seed=attempt_seed, 
                    stream=True, 
                    extra_body={
                        'min_p': self.cfg.min_p, 
                        'stop_token_ids': self.stop_token_ids, 
                        'return_token_ids': True
                    }
                )
    
                try:
                    token_buffer = []
                    text_chunks = []
    
                    for chunk in stream:
                        if stop_event.is_set() or time.time() > deadline:
                            break
    
                        new_tokens = chunk.choices[0].token_ids
                        new_text = chunk.choices[0].text
    
                        if new_tokens:
                            token_buffer.extend(new_tokens)
                            total_tokens += len(new_tokens)
                            text_chunks.append(new_text)
                            
                            chunk_logprobs = chunk.choices[0].logprobs
                            
                            if chunk_logprobs is not None:
                                if chunk_logprobs.top_logprobs:
                                    logprobs_buffer.extend(chunk_logprobs.top_logprobs)
    
                        if '}' in new_text:
                            search_text = ''.join(text_chunks[-self.cfg.search_tokens:])
                            answer = self._scan_for_answer(search_text)
    
                            if answer is not None:
                                final_answer = answer
                                break
    
                finally:
                    stream.close()
    
                if final_answer is not None:
                    break
    
                if not token_buffer:
                    break
    
                new_messages = encoding.parse_messages_from_completion_tokens(token_buffer, Role.ASSISTANT)
                conversation.messages.extend(new_messages)
                last_message = new_messages[-1]
    
                if last_message.channel == 'final':
                    answer_text = last_message.content[0].text
                    final_answer = self._scan_for_answer(answer_text)
                    break
    
                if last_message.recipient == 'python':
                    python_calls += 1
                    tool_responses = local_tool.process_sync_plus(last_message)
    
                    response_text = tool_responses[0].content[0].text
    
                    if response_text.startswith('[ERROR]') or 'Traceback' in response_text or 'Error:' in response_text:
                        python_errors += 1
    
                    conversation.messages.extend(tool_responses)
    
        except Exception as exc:
            python_errors += 1
    
        finally:
            if sandbox is not None:
                sandbox.reset()
                self.sandbox_pool.put(sandbox)
    
        mean_entropy = self._compute_mean_entropy(logprobs_buffer)
    
        return {
            'Attempt': attempt_index + 1, 
            'Response Length': total_tokens, 
            'Python Calls': python_calls, 
            'Python Errors': python_errors, 
            'Entropy': mean_entropy, 
            'Answer': final_answer
        }
    
    def _select_answer(self, detailed_results: list) -> int:

        answer_weights = defaultdict(float)
        answer_votes = defaultdict(int)

        for result in detailed_results:
            answer = result['Answer']
            entropy = result['Entropy']
            
            if answer is not None:
                weight = 1.0 / max(entropy, 1e-9)
                
                answer_weights[answer] += weight
                answer_votes[answer] += 1

        scored_answers = []

        for answer, total_weight in answer_weights.items():
            scored_answers.append({
                'answer': answer, 
                'votes': answer_votes[answer], 
                'score': total_weight
            })

        scored_answers.sort(key=lambda x: x['score'], reverse=True)

        vote_data = []

        for item in scored_answers:
            vote_data.append((
                item['answer'], 
                item['votes'], 
                item['score']
            ))

        vote_dataframe = pd.DataFrame(
            vote_data, 
            columns=['Answer', 'Votes', 'Score']
        )

        vote_dataframe = vote_dataframe.round({'Score': 3})
        display(vote_dataframe)
        
        if not scored_answers:
            print('\nFinal Answer: 0\n')
            return 0

        final_answer = scored_answers[0]['answer']    
        print(f'\nFinal Answer: {final_answer}\n')

        return final_answer
    
    def solve_problem(self, problem: str) -> int:
    
        print(f'\nProblem: {problem}\n')
        
        user_input = f'{problem} {self.cfg.preference_prompt}'
    
        elapsed_global = time.time() - self.notebook_start_time
        time_left = self.cfg.notebook_limit - elapsed_global
        problems_left_others = max(0, self.problems_remaining - 1)
        reserved_time = problems_left_others * self.cfg.base_problem_timeout
    
        budget = time_left - reserved_time
        budget = min(budget, self.cfg.high_problem_timeout)
        budget = max(budget, self.cfg.base_problem_timeout)
    
        deadline = time.time() + budget
    
        print(f'Budget: {budget:.2f} seconds | Deadline: {deadline:.2f}\n')
    
        tasks = []
    
        for attempt_index in range(self.cfg.attempts):
            tasks.append((self.cfg.system_prompt, attempt_index))
    
        detailed_results = []
        valid_answers = []
    
        stop_event = threading.Event()
    
        executor = ThreadPoolExecutor(max_workers=self.cfg.workers)
    
        try:
            futures = []
    
            for (system_prompt, attempt_index) in tasks:
                future = executor.submit(
                    self._process_attempt, 
                    user_input, 
                    system_prompt, 
                    attempt_index, 
                    stop_event, 
                    deadline
                )
    
                futures.append(future)
    
            for future in as_completed(futures):
                try:
                    result = future.result()
                    detailed_results.append(result)
    
                    if result['Answer'] is not None:
                        valid_answers.append(result['Answer'])
    
                    counts = Counter(valid_answers).most_common(1)
    
                    if counts and counts[0][1] >= self.cfg.early_stop:
                        stop_event.set()
    
                        for f in futures:
                            f.cancel()
    
                        break
    
                except Exception as exc:
                    print(f'Future failed: {exc}')
                    continue
    
        finally:
            stop_event.set()
            executor.shutdown(wait=True, cancel_futures=True)
            
            self.problems_remaining = max(0, self.problems_remaining - 1)
    
        if detailed_results:
            results_dataframe = pd.DataFrame(detailed_results)
            results_dataframe['Entropy'] = results_dataframe['Entropy'].round(3)
            results_dataframe['Answer'] = results_dataframe['Answer'].astype('Int64')
            
            display(results_dataframe)
    
        if not valid_answers:
            print('\nResult: 0\n')
    
            return 0
    
        return self._select_answer(detailed_results)
    
    def __del__(self):
    
        if hasattr(self, 'server_process'):
            self.server_process.terminate()
            self.server_process.wait()
    
        if hasattr(self, 'log_file'):
            self.log_file.close()
    
        if hasattr(self, 'sandbox_pool'):
            while not self.sandbox_pool.empty():
                try:
                    sb = self.sandbox_pool.get_nowait()
                    sb.close()
    
                except Exception:
                    pass

In [15]:
solver = AIMO3Solver(CFG)

Loading model weights from /kaggle/input/gpt-oss-120b/transformers/default/1 into OS Page Cache...
Processed 26 files (65.28 GB) in 63.44 seconds.

Waiting for vLLM server...
Server is ready (took 126.11 seconds).

Initializing 16 persistent Jupyter kernels...
Kernels initialized in 2.90 seconds.

In [16]:
def predict(id_: pl.DataFrame, question: pl.DataFrame, answer: Optional[pl.DataFrame] = None) -> pl.DataFrame:
    
    id_value = id_.item(0)
    question_text = question.item(0)
    
    gc.disable()
    
    final_answer = solver.solve_problem(question_text)
    
    gc.enable()
    gc.collect()
    
    return pl.DataFrame({'id': id_value, 'answer': final_answer})

In [17]:
inference_server = kaggle_evaluation.aimo_3_inference_server.AIMO3InferenceServer(predict)

if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
    inference_server.serve()
    
else:
    inference_server.run_local_gateway(
        ('/kaggle/input/ai-mathematical-olympiad-progress-prize-3/test.csv',)
    )

Problem: What is $1-1$?

Budget: 900.00 seconds | Deadline: 1776598271.54

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8              115             0              0    0.663       0
1        5              136             0              0    0.736       0
2        4              156             0              0    0.843       0
3        6              169             0              0    0.745       0

   Answer  Votes  Score
0       0      4  5.395

Final Answer: 0


Problem: What is $0\times10$?

Budget: 900.00 seconds | Deadline: 1776598288.61

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8               97             0              0    0.593       0
1        4              100             0              0    0.602       0
2        3              134             0              0    0.766       0
3        6              151             0              0    0.814       0

   Answer  Votes  Score
0       0      4  5.881

Final Answer: 0


Problem: Solve $4+x=4$ for $x$.

Budget: 900.00 seconds | Deadline: 1776598290.50

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6              124             0              0    0.645       0
1        7              132             0              0    0.657       0
2        5              181             0              0    0.712       0
3        2              187             0              0    0.686       0

   Answer  Votes  Score
0       0      4  5.934

Final Answer: 0

In [18]:
import csv

data = [
    ["id", "problem", "answer"],

    # --- TMO 2025 Problems ---
    ["tmo_2025_01", "In a triangle $ABC$, let $H$ be the orthocenter and $G$ be the centroid. If $|BH| = 3\\sqrt{2}$, $|CH| = 6$, and \\angle BHC = 135^\\circ$, what is $|GH|$?", "2"],
    ["tmo_2025_12", "Let $k$ be a positive integer. One of the numbers $1, 2, \\dots, k$ is written in each unit square of a $4 \\times 4$ chessboard. If for every pair $(m,n)$ satisfying $1 \\le m < n \\le k$, there exists a row or a column containing both $m$ and $n$, what is the maximum possible value of $k$?", "8"],

    ["tmo_2025_02", "How many positive integers $n < 2025$ are there such that the number $1^3 + 2^3 + \\dots + n^3$ is divisible by $2025$?", "179"],
    ["reference_10", "Let $n \\ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define\n\\begin{equation*}\ng(c) = \\frac{1}{2025!} \\left\\lfloor \\frac{2025! f(M+c)}{M} \\right\\rfloor.\n\\end{equation*}\nWe can write\n\\begin{equation*}\ng(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \\frac{p}{q}\n\\end{equation*}\nwhere $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?", "8687"],
    ["imo_2025_01_mod", "A line in the plane is called sunny if it is not parallel to any of the $x$-axis, the $y$-axis, and the line $x + y = 0$. Let $n \\ge 3$ be a given integer. Determine the sum of all possible nonnegative integers $k$ such that there exist $n$ distinct lines in the plane satisfying both of the following: for all positive integers $a$ and $b$ with $a + b \\le n + 1$, the point $(a, b)$ is on at least one of the lines; and exactly $k$ of the $n$ lines are sunny.", "4"],

    ["tmo_2025_03", "Let $m$ and $n$ be integers. How many polynomials $f(x) = x^2 + mx + n$ satisfy the condition $f(f(360)) = 0$?", "48"],
    ["tmo_2025_04", "A person with 6 different hats wears one of these hats each day for 6 consecutive days. This person wears different hats on any two consecutive days, but wears the same hat on the first and the last day. In how many different sequences can this person wear the hats over these 6 days?", "3120"],
        ["reference_10", "Let $n \\ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define\n\\begin{equation*}\ng(c) = \\frac{1}{2025!} \\left\\lfloor \\frac{2025! f(M+c)}{M} \\right\\rfloor.\n\\end{equation*}\nWe can write\n\\begin{equation*}\ng(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \\frac{p}{q}\n\\end{equation*}\nwhere $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?", "8687"],

    ["tmo_2025_05", "In a cyclic pentagon $ABCDE$, the conditions $AB \\parallel CE$ and $AC \\parallel DE$ are satisfied. Let $F$ be the intersection point of the lines $AB$ and $CD$. If $|CF| = 8$, $|CD| = 12$, and $|DE| = 30$, what is $|AC|$?", "20"],
    ["tmo_2025_06", "For how many of the numbers $n \\in \\{195, 196, 197, 198, 199, 200\\}$ is the number $1^n + 2^{n-1} + 3^{n-2} + \\dots + n^1$ divisible by 3?", "4"],
    ["imo_2025_05_mod", "Alice and Bazza are playing a two-player game whose rules depend on a positive real number $\\lambda$ which is known to both players. On the $n^{\\text{th}}$ turn of the game (starting with $n = 1$) the following happens: If $n$ is odd, Alice chooses a nonnegative real number $x_n$ such that $x_1 + x_2 + \\dots + x_n \\le \\lambda n$. If $n$ is even, Bazza chooses a nonnegative real number $x_n$ such that $x_1^2 + x_2^2 + \\dots + x_n^2 \\le n$. If a player cannot choose a suitable number $x_n$, the game ends and the other player wins. If the game goes on forever, neither player wins. All chosen numbers are known to both players. There is a critical threshold $\\lambda_c$ such that Alice has a winning strategy if $\\lambda > \\lambda_c$, and Bazza has a winning strategy if $0 < \\lambda < \\lambda_c$. If $\\lambda_c$ can be written in the form $\\frac{1}{\\sqrt{m}}$ for some integer $m$, what is the value of $m$?", "2"],

    ["tmo_2025_07", "For how many positive integers $a$ does the polynomial $P(x) = x^6 - 6x^5 + 12x^4 - ax^3 + 12x^2 - 6x + 1$ have no positive real roots?", "11"],
    ["tmo_2025_10", "How many ordered pairs of positive integers $(a,b)$ satisfy the conditions $\\gcd(a,b) = 22!$ and $\\text{lcm}(a,b) = 33!$?", "512"],
    ["tmo_2025_12", "Let $k$ be a positive integer. One of the numbers $1, 2, \\dots, k$ is written in each unit square of a $4 \\times 4$ chessboard. If for every pair $(m,n)$ satisfying $1 \\le m < n \\le k$, there exists a row or a column containing both $m$ and $n$, what is the maximum possible value of $k$?", "8"],
    ["reference_10", "Let $n \\ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define\n\\begin{equation*}\ng(c) = \\frac{1}{2025!} \\left\\lfloor \\frac{2025! f(M+c)}{M} \\right\\rfloor.\n\\end{equation*}\nWe can write\n\\begin{equation*}\ng(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \\frac{p}{q}\n\\end{equation*}\nwhere $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?", "8687"],

    ["tmo_2025_13", "In a triangle $ABC$, let $|AB| = 2$ and $|AC| = 1$. A point $M$ located on the opposite side of the line $AB$ from $C$ satisfies $\\angle MAB = 90^\\circ$ and $|MA| = |AB|$. A point $N$ located on the opposite side of the line $AC$ from $B$ satisfies $\\angle NAC = 90^\\circ$ and $|NA| = |AC|$. Let $O$ be the circumcenter of the triangle $MNA$. If the lines $OA$ and $BC$ intersect at a point $D$, what is the ratio $\\frac{|BD|}{|CD|}$?", "4"],
    ["tmo_2025_14", "For how many positive integers $n \\le 2025$ do there not exist positive integers $x$ and $y$ such that $3^x - 5^y$ is divisible by $n$?", "945"],
    ["tmo_2025_12", "Let $k$ be a positive integer. One of the numbers $1, 2, \\dots, k$ is written in each unit square of a $4 \\times 4$ chessboard. If for every pair $(m,n)$ satisfying $1 \\le m < n \\le k$, there exists a row or a column containing both $m$ and $n$, what is the maximum possible value of $k$?", "8"],

    ["tmo_2025_15", "A sequence of real numbers $a_0, a_1, a_2, \\dots$ is defined by $a_0 = 3$ and for all $n \\ge 1$,\n\\begin{equation*}\n\\frac{a_n + 1}{n} = \\frac{a_{n-1}^2}{n} + 2a_{n-1} + n - 1\n\\end{equation*}\nLet $k$ be a positive integer. What is the minimum possible value of the expression $|a_{2025} - 2^k|$?", "2026"],
    ["tmo_2025_19", "Let $k$ be an integer. How many different solutions are there to the equation\n\\begin{equation*}\n\\left\\lfloor \\frac{k+1}{2025} \\right\\rfloor + \\left\\lfloor \\frac{k+2}{2025} \\right\\rfloor + \\dots + \\left\\lfloor \\frac{k+2024}{2025} \\right\\rfloor = 2025!\n\\end{equation*}\n(For a real number $x$, $\\lfloor x \\rfloor$ denotes the greatest integer not exceeding $x$.)", "2"],
        ["reference_10", "Let $n \\ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define\n\\begin{equation*}\ng(c) = \\frac{1}{2025!} \\left\\lfloor \\frac{2025! f(M+c)}{M} \\right\\rfloor.\n\\end{equation*}\nWe can write\n\\begin{equation*}\ng(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \\frac{p}{q}\n\\end{equation*}\nwhere $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?", "8687"],

    ["tmo_2025_20", "For how many of the pairs $(m,n) \\in \\{(32, 33), (20, 25), (10, 40), (19, 21), (77, 99)\\}$ can an $m \\times n$ chessboard be colored such that each unit square is painted either red or blue, and for every unit square, the number of its adjacent unit squares (sharing a common edge or a common vertex with it) that have the same color as itself is an odd number?", "3"],
    ["imo_2025_05_mod", "Alice and Bazza are playing a two-player game whose rules depend on a positive real number $\\lambda$ which is known to both players. On the $n^{\\text{th}}$ turn of the game (starting with $n = 1$) the following happens: If $n$ is odd, Alice chooses a nonnegative real number $x_n$ such that $x_1 + x_2 + \\dots + x_n \\le \\lambda n$. If $n$ is even, Bazza chooses a nonnegative real number $x_n$ such that $x_1^2 + x_2^2 + \\dots + x_n^2 \\le n$. If a player cannot choose a suitable number $x_n$, the game ends and the other player wins. If the game goes on forever, neither player wins. All chosen numbers are known to both players. There is a critical threshold $\\lambda_c$ such that Alice has a winning strategy if $\\lambda > \\lambda_c$, and Bazza has a winning strategy if $0 < \\lambda < \\lambda_c$. If $\\lambda_c$ can be written in the form $\\frac{1}{\\sqrt{m}}$ for some integer $m$, what is the value of $m$?", "2"],

    ["tmo_2025_21", "The inscribed circle of a right-angled triangle $ABC$ with $\\angle B = 90^\\circ$ is tangent to the sides $AB$ and $AC$ at points $D$ and $E$, respectively. Let $F$ be the intersection point of the lines $ED$ and $BC$. If $|FD| = 25$ and $|DE| = 24$, what is $|AE|$?", "20"],
    ["imo_2025_01_mod", "A line in the plane is called sunny if it is not parallel to any of the $x$-axis, the $y$-axis, and the line $x + y = 0$. Let $n \\ge 3$ be a given integer. Determine the sum of all possible nonnegative integers $k$ such that there exist $n$ distinct lines in the plane satisfying both of the following: for all positive integers $a$ and $b$ with $a + b \\le n + 1$, the point $(a, b)$ is on at least one of the lines; and exactly $k$ of the $n$ lines are sunny.", "4"],

    ["tmo_2025_22", "Let $f(n)$ be the greatest odd divisor of a positive integer $n$. What is the sum $f(25) + f(26) + f(27) + \\dots + f(200)$?", "13150"],
    ["tmo_2025_23", "If positive real numbers $x$, $y$, and $z$ satisfy the system of equations\n\\begin{equation*}\n\\begin{aligned}\n\\frac{y^2}{z} + \\frac{zx+x^2}{2y+z} &= 2x \\\\\\\\\n\\frac{x^2}{z} + \\frac{zy+2y^2}{x+z} &= 9y \\\\\\\\\n\\frac{y^2}{x} + \\frac{x^2}{y} &= 9z\n\\end{aligned}\n\\end{equation*}\nwhat is the value of $\\frac{y}{x} + \\frac{z}{y} + \\frac{x}{z}$?", "5"],
    ["reference_10", "Let $n \\ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define\n\\begin{equation*}\ng(c) = \\frac{1}{2025!} \\left\\lfloor \\frac{2025! f(M+c)}{M} \\right\\rfloor.\n\\end{equation*}\nWe can write\n\\begin{equation*}\ng(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \\frac{p}{q}\n\\end{equation*}\nwhere $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?", "8687"],

    ["tmo_2025_26", "Let $p$ be a prime number, and let $f(p)$ be the number of integers $x$ that satisfy the condition $x + p^2 \\mid x^3 + p^4$. For how many of the numbers $m \\in \\{150, 160, 170, 180, 190\\}$ does there exist a prime number $p$ such that $f(p) = m$?", "2"],
    ["tmo_2025_27", "Initially, there is 1 liter of a homogeneous mixture in a blue jar consisting of $99\\%$ pomegranate juice and $1\\%$ orange juice, and 2 liters of a homogeneous mixture in a green jar consisting of $1\\%$ pomegranate juice and $99\\%$ orange juice. In each step, first, 1 liter of mixture is transferred from the green jar to the blue jar and mixed until it is homogeneous. Then, 1 liter of mixture is transferred from the blue jar back to the green jar and mixed until it is homogeneous. After at least how many steps will the absolute difference between the percentage of pomegranate juice in the blue jar and the percentage of pomegranate juice in the green jar be strictly less than $0.1\\%$?", "5"],
    ["reference_10", "Let $n \\ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define\n\\begin{equation*}\ng(c) = \\frac{1}{2025!} \\left\\lfloor \\frac{2025! f(M+c)}{M} \\right\\rfloor.\n\\end{equation*}\nWe can write\n\\begin{equation*}\ng(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \\frac{p}{q}\n\\end{equation*}\nwhere $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?", "8687"],

    ["tmo_2025_28", "25 points are marked on a circle with a circumference of 25 units such that these points are the vertices of a regular 25-gon, and $k$ of these points are colored red. If, regardless of how this coloring is done, there are always two red points such that the length of the shorter arc between them is 5 units, what is the minimum possible value of $k$?", "11"],
    ["tmo_2025_30", "How many integers $n$ are there such that the expression $n^4 - 5n^3 + 26n^2 - 41n + 19$ is equal to an integer power of a prime number?", "3"],
    ["tmo_2025_32", "A $1 \\times N$ chessboard, with initially no unit squares colored, is drawn on a board. Two players, $A$ and $B$, play a game by taking turns making moves, with player $A$ starting the game. In their turn, player $A$ colors an uncolored unit square red, and player $B$ colors an uncolored unit square blue in their turn. Neither player is allowed to make a move such that two unit squares sharing a common edge have the same color. The player who cannot make a move loses the game. If the game is played exactly once for each of the values $N \\in \\{2023, 2024, 2025, 2026, 2027\\}$, how many of these games can player $A$ guarantee to win?", "0"],

    # --- New Reference Problems ---
    ["reference_01", "Alice and Bob are each holding some integer number of sweets. Alice says to Bob: \"If we each added the number of sweets we're holding to our (positive integer) age, my answer would be double yours. If we took the product, then my answer would be four times yours.\" Bob replies: \"Why don't you give me five of your sweets because then both our sum and product would be equal.\" What is the product of Alice and Bob's ages?", "50"],
    ["reference_02", "A $500 \\times 500$ square is divided into $k$ rectangles, each having integer side lengths. Given that no two of these rectangles have the same perimeter, the largest possible value of $k$ is $\\mathcal{K}$. What is the remainder when $\\mathcal{K}$ is divided by $10^5$?", "520"],
    ["reference_03", "Let $ABC$ be an acute-angled triangle with integer side lengths and $AB < AC$. Points $D$ and $E$ lie on segments $BC$ and $AC$, respectively, such that $AD = AE = AB$. Line $DE$ intersects $AB$ at $X$. Circles $BXD$ and $CED$ intersect for the second time at $Y \\neq D$. Suppose that $Y$ lies on line $AD$. There is a unique such triangle with minimal perimeter. This triangle has side lengths $a = BC$, $b = CA$, and $c = AB$. Find the remainder when $abc$ is divided by $10^5$.", "336"],
    ["reference_10", "Let $n \\ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define\n\\begin{equation*}\ng(c) = \\frac{1}{2025!} \\left\\lfloor \\frac{2025! f(M+c)}{M} \\right\\rfloor.\n\\end{equation*}\nWe can write\n\\begin{equation*}\ng(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \\frac{p}{q}\n\\end{equation*}\nwhere $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?", "8687"],

    ["reference_04", "Let $f \\colon \\mathbb{Z}_{\\ge 1} \\to \\mathbb{Z}_{\\ge 1}$ be a function such that for all positive integers $m$ and $n$,\n\\begin{equation*}\nf(m) + f(n) = f(m + n + mn).\n\\end{equation*}\nAcross all functions $f$ such that $f(n) \\le 1000$ for all $n \\le 1000$, how many different values can $f(2024)$ take?", "580"],
    ["reference_05", "A tournament is held with $2^{20}$ runners each of which has a different running speed. In each race, two runners compete against each other with the faster runner always winning the race. The competition consists of 20 rounds with each runner starting with a score of 0. In each round, the runners are paired in such a way that in each pair, both runners have the same score at the beginning of the round. The winner of each race in the $i^{\\text{th}}$ round receives $2^{20-i}$ points and the loser gets no points.\n\nAt the end of the tournament, we rank the competitors according to their scores. Let $N$ denote the number of possible orderings of the competitors at the end of the tournament. Let $k$ be the largest positive integer such that $10^k$ divides $N$. What is the remainder when $k$ is divided by $10^5$?", "21818"],
    ["imo_2025_01_mod", "A line in the plane is called sunny if it is not parallel to any of the $x$-axis, the $y$-axis, and the line $x + y = 0$. Let $n \\ge 3$ be a given integer. Determine the sum of all possible nonnegative integers $k$ such that there exist $n$ distinct lines in the plane satisfying both of the following: for all positive integers $a$ and $b$ with $a + b \\le n + 1$, the point $(a, b)$ is on at least one of the lines; and exactly $k$ of the $n$ lines are sunny.", "4"],

    ["reference_06", "Define a function $f \\colon \\mathbb{Z}_{\\ge 1} \\to \\mathbb{Z}_{\\ge 1}$ by\n\\begin{equation*}\nf(n) = \\sum_{i=1}^n \\sum_{j=1}^n j^{1024} \\left\\lfloor \\frac{1}{j} + \\frac{n-i}{n} \\right\\rfloor.\n\\end{equation*}\nLet $M = 2 \\cdot 3 \\cdot 5 \\cdot 7 \\cdot 11 \\cdot 13$ and let $N = f(M^{15}) - f(M^{15} - 1)$. Let $k$ be the largest non-negative integer such that $2^k$ divides $N$. What is the remainder when $2^k$ is divided by $5^7$?", "32951"],
    ["reference_07", "Let $ABC$ be a triangle with $AB \\neq AC$, circumcircle $\\Omega$, and incircle $\\omega$. Let the contact points of $\\omega$ with $BC$, $CA$, and $AB$ be $D$, $E$, and $F$, respectively. Let the circumcircle of $AFE$ meet $\\Omega$ at $K$ and let the reflection of $K$ in $EF$ be $K'$. Let $N$ denote the foot of the perpendicular from $D$ to $EF$. The circle tangent to line $BN$ and passing through $B$ and $K$ intersects $BC$ again at $T \\neq B$.\n\nLet sequence $(F_n)_{n \\ge 0}$ be defined by $F_0 = 0$, $F_1 = 1$ and for $n \\ge 2$, $F_n = F_{n-1} + F_{n-2}$. Call $ABC$ $n$\\emph{-tastic} if $BD = F_n$, $CD = F_{n+1}$, and $KNK'B$ is cyclic. Across all $n$-tastic triangles, let $a_n$ denote the maximum possible value of $\\frac{CT \\cdot NB}{BT \\cdot NE}$. Let $\\alpha$ denote the smallest real number such that for all sufficiently large $n$, $a_{2n} < \\alpha$. Given that $\\alpha = p + \\sqrt{q}$ for rationals $p$ and $q$, what is the remainder when $\\left\\lfloor p^{q^p} \\right\\rfloor$ is divided by $99991$?", "57447"],
    ["reference_08", "On a blackboard, Ken starts off by writing a positive integer $n$ and then applies the following move until he first reaches $1$. Given that the number on the board is $m$, he chooses a base $b$, where $2 \\le b \\le m$, and considers the unique base-$b$ representation of $m$,\n\\begin{equation*}\nm = \\sum_{k=0}^\\infty a_k \\cdot b^k\n\\end{equation*}\nwhere $a_k$ are non-negative integers and $0 \\le a_k < b$ for each $k$. Ken then erases $m$ on the blackboard and replaces it with $\\sum_{k=0}^\\infty a_k$.\n\nAcross all choices of $1 \\le n \\le 10^{10^5}$, the largest possible number of moves Ken could make is $M$. What is the remainder when $M$ is divided by $10^5$?", "32193"],
    ["tmo_2025_12", "Let $k$ be a positive integer. One of the numbers $1, 2, \\dots, k$ is written in each unit square of a $4 \\times 4$ chessboard. If for every pair $(m,n)$ satisfying $1 \\le m < n \\le k$, there exists a row or a column containing both $m$ and $n$, what is the maximum possible value of $k$?", "8"],

    ["reference_09", "Let $\\mathcal{F}$ be the set of functions $\\alpha \\colon \\mathbb{Z} \\to \\mathbb{Z}$ for which there are only finitely many $n \\in \\mathbb{Z}$ such that $\\alpha(n) \\neq 0$.\n\nFor two functions $\\alpha$ and $\\beta$ in $\\mathcal{F}$, define their product $\\alpha \\star \\beta$ to be $\\sum_{n \\in \\mathbb{Z}} \\alpha(n) \\cdot \\beta(n)$. Also, for $n \\in \\mathbb{Z}$, define a shift operator $S_n \\colon \\mathcal{F} \\to \\mathcal{F}$ by $S_n(\\alpha)(t) = \\alpha(t+n)$ for all $t \\in \\mathbb{Z}$.\n\nA function $\\alpha \\in \\mathcal{F}$ is called \\emph{shifty} if\n\\begin{itemize}\n\\item $\\alpha(m) = 0$ for all integers $m < 0$ and $m > 8$ and\n\\item There exists $\\beta \\in \\mathcal{F}$ and integers $k \\neq l$ such that for all $n \\in \\mathbb{Z}$\n\\begin{equation*}\nS_n(\\alpha) \\star \\beta = \\begin{cases} 1 & n \\in \\{k,l\\} \\\\\\\\ 0 & n \\notin \\{k,l\\} \\end{cases}.\n\\end{equation*}\n\\end{itemize}\nHow many shifty functions are there in $\\mathcal{F}$?", "160"],
    ["reference_10", "Let $n \\ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define\n\\begin{equation*}\ng(c) = \\frac{1}{2025!} \\left\\lfloor \\frac{2025! f(M+c)}{M} \\right\\rfloor.\n\\end{equation*}\nWe can write\n\\begin{equation*}\ng(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \\frac{p}{q}\n\\end{equation*}\nwhere $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?", "8687"],
        # Reformulated Problem 1
    ["imo_2025_01_mod", "A line in the plane is called sunny if it is not parallel to any of the $x$-axis, the $y$-axis, and the line $x + y = 0$. Let $n \\ge 3$ be a given integer. Determine the sum of all possible nonnegative integers $k$ such that there exist $n$ distinct lines in the plane satisfying both of the following: for all positive integers $a$ and $b$ with $a + b \\le n + 1$, the point $(a, b)$ is on at least one of the lines; and exactly $k$ of the $n$ lines are sunny.", "4"],

    # Problem 3
    ["imo_2025_03", "Let $\\mathbb{N}$ denote the set of positive integers. A function $f \\colon \\mathbb{N} \\to \\mathbb{N}$ is said to be bonza if $f(a)$ divides $b^a - f(b)^{f(a)}$ for all positive integers $a$ and $b$. Determine the smallest real constant $c$ such that $f(n) \\le cn$ for all bonza functions $f$ and all positive integers $n$.", "4"],

    # Reformulated Problem 5
    ["imo_2025_05_mod", "Alice and Bazza are playing a two-player game whose rules depend on a positive real number $\\lambda$ which is known to both players. On the $n^{\\text{th}}$ turn of the game (starting with $n = 1$) the following happens: If $n$ is odd, Alice chooses a nonnegative real number $x_n$ such that $x_1 + x_2 + \\dots + x_n \\le \\lambda n$. If $n$ is even, Bazza chooses a nonnegative real number $x_n$ such that $x_1^2 + x_2^2 + \\dots + x_n^2 \\le n$. If a player cannot choose a suitable number $x_n$, the game ends and the other player wins. If the game goes on forever, neither player wins. All chosen numbers are known to both players. There is a critical threshold $\\lambda_c$ such that Alice has a winning strategy if $\\lambda > \\lambda_c$, and Bazza has a winning strategy if $0 < \\lambda < \\lambda_c$. If $\\lambda_c$ can be written in the form $\\frac{1}{\\sqrt{m}}$ for some integer $m$, what is the value of $m$?", "2"]
]


with open("tmo_2025_aimo_dataset.csv", mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file, quoting=csv.QUOTE_MINIMAL)
    writer.writerows(data)

print("File 'tmo_2025_aimo_dataset.csv' created successfully with total problems!", len(data))

File 'tmo_2025_aimo_dataset.csv' created successfully with total problems! 51

In [19]:
import pandas as pd
import gc

# 1. Load your newly created dataset
df = pd.read_csv("tmo_2025_aimo_dataset.csv")

# 2. IMPORTANT: Update the solver's problem count! 
# The original code expects 50 problems and divides its 9-hour time limit accordingly. 
# Changing this to 10 ensures the solver gives maximum allowed time to your hard problems.
solver.problems_remaining = len(df)

results = []

print("\n" + "="*50)
print(f"STARTING EXPERIMENT ON {len(df)} CUSTOM PROBLEMS")
print("="*50 + "\n")

# 3. Loop through your CSV
for index, row in df.iterrows():
    problem_id = row['id']
    problem_text = row['problem']
    expected_answer = row['answer']
    
    print(f"\n--- Solving Problem {index + 1}/{len(df)}: {problem_id} ---")
    
    # Memory management identical to the original script
    gc.collect()
    gc.disable()
    
    # Generate the prediction
    predicted_answer = solver.solve_problem(problem_text)
    
    gc.enable()
    gc.collect()
    
    # Check correctness (cast both to strings to avoid type mismatch bugs)
    is_correct = str(expected_answer) == str(predicted_answer)
    
    # Store and display intermediate result
    results.append({
        'id': problem_id,
        'expected': expected_answer,
        'predicted': predicted_answer,
        'correct': is_correct
    })
    
    print(f">>> Expected: {expected_answer} | Predicted: {predicted_answer} | Correct: {is_correct}\n")

# 4. Final summary
results_df = pd.DataFrame(results)
print("\n" + "="*50)
print("=== FINAL EXPERIMENT SUMMARY ===")
print("="*50)
display(results_df)

accuracy = results_df['correct'].mean() * 100
print(f"\nOverall Accuracy: {accuracy:.2f}% ({results_df['correct'].sum()}/{len(df)} correct)")

==================================================
STARTING EXPERIMENT ON 50 CUSTOM PROBLEMS
==================================================


--- Solving Problem 1/50: tmo_2025_01 ---

Problem: In a triangle $ABC$, let $H$ be the orthocenter and $G$ be the centroid. If $|BH| = 3\sqrt{2}$, $|CH| = 6$, and \angle BHC = 135^\circ$, what is $|GH|$?

Budget: 900.00 seconds | Deadline: 1776598292.65

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             2947             7              0    0.575       2
1        8             3201             0              0    0.679       2
2        1             4134             2              0    0.581       2
3        7             5959             4              0    0.676       2

   Answer  Votes  Score
0       2      4  6.414

Final Answer: 2

>>> Expected: 2 | Predicted: 2 | Correct: True


--- Solving Problem 2/50: tmo_2025_12 ---

Problem: Let $k$ be a positive integer. One of the numbers $1, 2, \dots, k$ is written in each unit square of a $4 \times 4$ chessboard. If for every pair $(m,n)$ satisfying $1 \le m < n \le k$, there exists a row or a column containing both $m$ and $n$, what is the maximum possible value of $k$?

Budget: 900.00 seconds | Deadline: 1776598346.62

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            18795            12              5    0.786       8
1        6            21805            13              2    0.874       8
2        1            22580             8              0    0.861       8
3        2            32311            34              7    0.765       8

   Answer  Votes  Score
0       8      4  4.884

Final Answer: 8

>>> Expected: 8 | Predicted: 8 | Correct: True


--- Solving Problem 3/50: tmo_2025_02 ---

Problem: How many positive integers $n < 2025$ are there such that the number $1^3 + 2^3 + \dots + n^3$ is divisible by $2025$?

Budget: 900.00 seconds | Deadline: 1776598705.61

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             3694             3              0    0.766     179
1        1             4474             5              1    0.693     179
2        8             4518             4              0    0.667     179
3        4             4574             4              0    0.687     179

   Answer  Votes  Score
0     179      4  5.703

Final Answer: 179

>>> Expected: 179 | Predicted: 179 | Correct: True


--- Solving Problem 4/50: reference_10 ---

Problem: Let $n \ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define
\begin{equation*}
g(c) = \frac{1}{2025!} \left\lfloor \frac{2025! f(M+c)}{M} \right\rfloor.
\end{equation*}
We can write
\begin{equation*}
g(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \frac{p}{q}
\end{equation*}
where $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776598749.38

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4            23090            36              0    0.733    <NA>
1        3            29273            20              3    0.727    6825
2        1            38216            43              4    0.741   51082
3        8            38807            51              3    0.668    <NA>
4        7            39564            59              5    0.702   74763
5        2            44318            81              6    0.708   77463
6        5            53611            62              7    0.649    8687
7        6            60557            34              2    0.735    <NA>

   Answer  Votes  Score
0    8687      1  1.541
1   74763      1  1.425
2   77463      1  1.412
3    6825      1  1.376
4   51082      1  1.349

Final Answer: 8687

>>> Expected: 8687 | Predicted: 8687 | Correct: True


--- Solving Problem 5/50: imo_2025_01_mod ---

Problem: A line in the plane is called sunny if it is not parallel to any of the $x$-axis, the $y$-axis, and the line $x + y = 0$. Let $n \ge 3$ be a given integer. Determine the sum of all possible nonnegative integers $k$ such that there exist $n$ distinct lines in the plane satisfying both of the following: for all positive integers $a$ and $b$ with $a + b \le n + 1$, the point $(a, b)$ is on at least one of the lines; and exactly $k$ of the $n$ lines are sunny.

Budget: 900.00 seconds | Deadline: 1776599361.02

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5            13402             2              1    0.849       1
1        2            42883            31              5    0.777       4
2        4            48749            29              6    0.747       4
3        1            44394            47             15    0.669       6
4        7            51608            30              4    0.715       4
5        8            56162            47             10    0.713       4

   Answer  Votes  Score
0       4      4  5.426
1       6      1  1.496
2       1      1  1.178

Final Answer: 4

>>> Expected: 4 | Predicted: 4 | Correct: True


--- Solving Problem 6/50: tmo_2025_03 ---

Problem: Let $m$ and $n$ be integers. How many polynomials $f(x) = x^2 + mx + n$ satisfy the condition $f(f(360)) = 0$?

Budget: 900.00 seconds | Deadline: 1776600022.42

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             2566             3              0    0.608      48
1        1             3075             2              0    0.582      48
2        7             4254             2              0    0.696      48
3        8             5519             8              0    0.693      48

   Answer  Votes  Score
0      48      4  6.239

Final Answer: 48

>>> Expected: 48 | Predicted: 48 | Correct: True


--- Solving Problem 7/50: tmo_2025_04 ---

Problem: A person with 6 different hats wears one of these hats each day for 6 consecutive days. This person wears different hats on any two consecutive days, but wears the same hat on the first and the last day. In how many different sequences can this person wear the hats over these 6 days?

Budget: 900.00 seconds | Deadline: 1776600072.25

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             1954             1              0    0.855    3120
1        4             2026             1              0    0.641    3120
2        8             2327             2              0    0.681    3120
3        7             2351             2              0    0.672    3120

   Answer  Votes  Score
0    3120      4  5.685

Final Answer: 3120

>>> Expected: 3120 | Predicted: 3120 | Correct: True


--- Solving Problem 8/50: reference_10 ---

Problem: Let $n \ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define
\begin{equation*}
g(c) = \frac{1}{2025!} \left\lfloor \frac{2025! f(M+c)}{M} \right\rfloor.
\end{equation*}
We can write
\begin{equation*}
g(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \frac{p}{q}
\end{equation*}
where $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776600095.24

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            26694            39              1    0.688    1554
1        6            26341            31              3    0.754   18016
2        5            31854            40              1    0.761   43022
3        2            38835            55              1    0.735   96985
4        3            37184            52              9    0.727    8687
5        1            39883            49              1    0.721    8687
6        8            43780            44              5    0.676   51082
7        4            45411            38              2    0.735    <NA>

   Answer  Votes  Score
0    8687      2  2.763
1   51082      1  1.480
2    1554      1  1.454
3   96985      1  1.361
4   18016      1  1.326
5   43022      1  1.313

Final Answer: 8687

>>> Expected: 8687 | Predicted: 8687 | Correct: True


--- Solving Problem 9/50: tmo_2025_05 ---

Problem: In a cyclic pentagon $ABCDE$, the conditions $AB \parallel CE$ and $AC \parallel DE$ are satisfied. Let $F$ be the intersection point of the lines $AB$ and $CD$. If $|CF| = 8$, $|CD| = 12$, and $|DE| = 30$, what is $|AC|$?

Budget: 900.00 seconds | Deadline: 1776600582.00

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             9166             8              1    0.723      20
1        2            16838             8              0    0.817      20
2        4            18082            11              3    0.699      20
3        1            23063            10              2    0.772      20

   Answer  Votes  Score
0      20      4  5.333

Final Answer: 20

>>> Expected: 20 | Predicted: 20 | Correct: True


--- Solving Problem 10/50: tmo_2025_06 ---

Problem: For how many of the numbers $n \in \{195, 196, 197, 198, 199, 200\}$ is the number $1^n + 2^{n-1} + 3^{n-2} + \dots + n^1$ divisible by 3?

Budget: 900.00 seconds | Deadline: 1776600812.52

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5              876             2              0    0.750       4
1        8             1083             1              0    0.689       4
2        4             1763             3              0    0.708       4
3        1             3484             3              0    0.602       4

   Answer  Votes  Score
0       4      4  5.857

Final Answer: 4

>>> Expected: 4 | Predicted: 4 | Correct: True


--- Solving Problem 11/50: imo_2025_05_mod ---

Problem: Alice and Bazza are playing a two-player game whose rules depend on a positive real number $\lambda$ which is known to both players. On the $n^{\text{th}}$ turn of the game (starting with $n = 1$) the following happens: If $n$ is odd, Alice chooses a nonnegative real number $x_n$ such that $x_1 + x_2 + \dots + x_n \le \lambda n$. If $n$ is even, Bazza chooses a nonnegative real number $x_n$ such that $x_1^2 + x_2^2 + \dots + x_n^2 \le n$. If a player cannot choose a suitable number $x_n$, the game ends and the other player wins. If the game goes on forever, neither player wins. All chosen numbers are known to both players. There is a critical threshold $\lambda_c$ such that Alice has a winning strategy if $\lambda > \lambda_c$, and Bazza has a winning strategy if $0 < \lambda < \lambda_c$. If $\lambda_c$ can be written in the form $\frac{1}{\sqrt{m}}$ for some integer $m$, what is the value of $m$?

Budget: 900.00 seconds | Deadline: 1776600844.47

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2            25875            10              0    0.779       2
1        6            29724            11              0    0.715       2
2        7            34635             2              0    0.770       2
3        3            35631             9              0    0.755       2

   Answer  Votes  Score
0       2      4  5.307

Final Answer: 2

>>> Expected: 2 | Predicted: 2 | Correct: True


--- Solving Problem 12/50: tmo_2025_07 ---

Problem: For how many positive integers $a$ does the polynomial $P(x) = x^6 - 6x^5 + 12x^4 - ax^3 + 12x^2 - 6x + 1$ have no positive real roots?

Budget: 900.00 seconds | Deadline: 1776601218.14

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             3577             1              0    0.609      11
1        1             3693             1              0    0.700      11
2        5             3953             1              0    0.608      11
3        7             4027             6              0    0.706      11

   Answer  Votes  Score
0      11      4  6.135

Final Answer: 11

>>> Expected: 11 | Predicted: 11 | Correct: True


--- Solving Problem 13/50: tmo_2025_10 ---

Problem: How many ordered pairs of positive integers $(a,b)$ satisfy the conditions $\gcd(a,b) = 22!$ and $\text{lcm}(a,b) = 33!$?

Budget: 900.00 seconds | Deadline: 1776601256.97

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             1557             5              1    0.727     512
1        1             2029             3              0    0.765     512
2        3             2169             3              0    0.675     512
3        6             2417             4              1    0.833     512

   Answer  Votes  Score
0     512      4  5.366

Final Answer: 512

>>> Expected: 512 | Predicted: 512 | Correct: True


--- Solving Problem 14/50: tmo_2025_12 ---

Problem: Let $k$ be a positive integer. One of the numbers $1, 2, \dots, k$ is written in each unit square of a $4 \times 4$ chessboard. If for every pair $(m,n)$ satisfying $1 \le m < n \le k$, there exists a row or a column containing both $m$ and $n$, what is the maximum possible value of $k$?

Budget: 900.00 seconds | Deadline: 1776601281.18

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6            17930             6              0    0.875       8
1        1            18271             5              0    0.840       8
2        5            34638            20              3    0.844       8
3        8            36710            20              3    0.864       8

   Answer  Votes  Score
0       8      4  4.675

Final Answer: 8

>>> Expected: 8 | Predicted: 8 | Correct: True


--- Solving Problem 15/50: reference_10 ---

Problem: Let $n \ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define
\begin{equation*}
g(c) = \frac{1}{2025!} \left\lfloor \frac{2025! f(M+c)}{M} \right\rfloor.
\end{equation*}
We can write
\begin{equation*}
g(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \frac{p}{q}
\end{equation*}
where $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776601668.34

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            35415            21              1    0.715      47
1        5            45865            64              4    0.703    8687
2        4            46618            48              4    0.730    <NA>
3        3            51344            26              2    0.744      23
4        2            48978            68             10    0.654    <NA>
5        1            50601            94              7    0.705    <NA>
6        6            54683            33              4    0.744      79
7        8            60149            49              3    0.685   42534

   Answer  Votes  Score
0   42534      1  1.460
1    8687      1  1.422
2      47      1  1.398
3      79      1  1.344
4      23      1  1.344

Final Answer: 42534

>>> Expected: 8687 | Predicted: 42534 | Correct: False


--- Solving Problem 16/50: tmo_2025_13 ---

Problem: In a triangle $ABC$, let $|AB| = 2$ and $|AC| = 1$. A point $M$ located on the opposite side of the line $AB$ from $C$ satisfies $\angle MAB = 90^\circ$ and $|MA| = |AB|$. A point $N$ located on the opposite side of the line $AC$ from $B$ satisfies $\angle NAC = 90^\circ$ and $|NA| = |AC|$. Let $O$ be the circumcenter of the triangle $MNA$. If the lines $OA$ and $BC$ intersect at a point $D$, what is the ratio $\frac{|BD|}{|CD|}$?

Budget: 900.00 seconds | Deadline: 1776602336.18

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             2834             3              0    0.702       4
1        6             3029             3              0    0.643       4
2        4             3124             4              0    0.677       4
3        1             3290             0              0    0.608       4

   Answer  Votes  Score
0       4      4  6.103

Final Answer: 4

>>> Expected: 4 | Predicted: 4 | Correct: True


--- Solving Problem 17/50: tmo_2025_14 ---

Problem: For how many positive integers $n \le 2025$ do there not exist positive integers $x$ and $y$ such that $3^x - 5^y$ is divisible by $n$?

Budget: 900.00 seconds | Deadline: 1776602367.12

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8             3937             2              0    0.791     945
1        6             5192             3              1    0.649     945
2        3             5210             5              0    0.705     945
3        5             5624             1              0    0.664     945

   Answer  Votes  Score
0     945      4  5.729

Final Answer: 945

>>> Expected: 945 | Predicted: 945 | Correct: True


--- Solving Problem 18/50: tmo_2025_12 ---

Problem: Let $k$ be a positive integer. One of the numbers $1, 2, \dots, k$ is written in each unit square of a $4 \times 4$ chessboard. If for every pair $(m,n)$ satisfying $1 \le m < n \le k$, there exists a row or a column containing both $m$ and $n$, what is the maximum possible value of $k$?

Budget: 900.00 seconds | Deadline: 1776602420.45

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6            12167            12              0    0.847       8
1        4            18635             3              0    0.878       8
2        1            22388            16              4    0.873       8
3        5            30059            10              2    0.825       8

   Answer  Votes  Score
0       8      4  4.677

Final Answer: 8

>>> Expected: 8 | Predicted: 8 | Correct: True


--- Solving Problem 19/50: tmo_2025_15 ---

Problem: A sequence of real numbers $a_0, a_1, a_2, \dots$ is defined by $a_0 = 3$ and for all $n \ge 1$,
\begin{equation*}
\frac{a_n + 1}{n} = \frac{a_{n-1}^2}{n} + 2a_{n-1} + n - 1
\end{equation*}
Let $k$ be a positive integer. What is the minimum possible value of the expression $|a_{2025} - 2^k|$?

Budget: 900.00 seconds | Deadline: 1776602723.45

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             1801             0              0    0.490    2026
1        3             2001             0              0    0.604    2026
2        6             2349             1              0    0.499    2026
3        1             3205             1              0    0.616    2026

   Answer  Votes  Score
0    2026      4  7.324

Final Answer: 2026

>>> Expected: 2026 | Predicted: 2026 | Correct: True


--- Solving Problem 20/50: tmo_2025_19 ---

Problem: Let $k$ be an integer. How many different solutions are there to the equation
\begin{equation*}
\left\lfloor \frac{k+1}{2025} \right\rfloor + \left\lfloor \frac{k+2}{2025} \right\rfloor + \dots + \left\lfloor \frac{k+2024}{2025} \right\rfloor = 2025!
\end{equation*}
(For a real number $x$, $\lfloor x \rfloor$ denotes the greatest integer not exceeding $x$.)

Budget: 900.00 seconds | Deadline: 1776602752.90

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             3601             0              0    0.697       2
1        4             4448             2              0    0.629       2
2        3             5430             9              0    0.712       2
3        5             6372             2              0    0.706       2

   Answer  Votes  Score
0       2      4  5.847

Final Answer: 2

>>> Expected: 2 | Predicted: 2 | Correct: True


--- Solving Problem 21/50: reference_10 ---

Problem: Let $n \ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define
\begin{equation*}
g(c) = \frac{1}{2025!} \left\lfloor \frac{2025! f(M+c)}{M} \right\rfloor.
\end{equation*}
We can write
\begin{equation*}
g(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \frac{p}{q}
\end{equation*}
where $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776602812.25

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3            29212            53              1    0.727   41754
1        7            32499            62              6    0.719   41754
2        2            40937            52              3    0.697   93764
3        1            42432            42              3    0.685   41754
4        4            48749            42              3    0.684   13657
5        8            57722            62              4    0.689    <NA>
6        6            60287            39              4    0.758    <NA>
7        5            59574            68             10    0.705    <NA>

   Answer  Votes  Score
0   41754      3  4.225
1   13657      1  1.463
2   93764      1  1.435

Final Answer: 41754

>>> Expected: 8687 | Predicted: 41754 | Correct: False


--- Solving Problem 22/50: tmo_2025_20 ---

Problem: For how many of the pairs $(m,n) \in \{(32, 33), (20, 25), (10, 40), (19, 21), (77, 99)\}$ can an $m \times n$ chessboard be colored such that each unit square is painted either red or blue, and for every unit square, the number of its adjacent unit squares (sharing a common edge or a common vertex with it) that have the same color as itself is an odd number?

Budget: 900.00 seconds | Deadline: 1776603498.82

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            13067            10              2    0.652       3
1        3            13092            10              2    0.659       3
2        6            14227             5              2    0.737       3
3        4            14849            17              4    0.692       3

   Answer  Votes  Score
0       3      4  5.854

Final Answer: 3

>>> Expected: 3 | Predicted: 3 | Correct: True


--- Solving Problem 23/50: imo_2025_05_mod ---

Problem: Alice and Bazza are playing a two-player game whose rules depend on a positive real number $\lambda$ which is known to both players. On the $n^{\text{th}}$ turn of the game (starting with $n = 1$) the following happens: If $n$ is odd, Alice chooses a nonnegative real number $x_n$ such that $x_1 + x_2 + \dots + x_n \le \lambda n$. If $n$ is even, Bazza chooses a nonnegative real number $x_n$ such that $x_1^2 + x_2^2 + \dots + x_n^2 \le n$. If a player cannot choose a suitable number $x_n$, the game ends and the other player wins. If the game goes on forever, neither player wins. All chosen numbers are known to both players. There is a critical threshold $\lambda_c$ such that Alice has a winning strategy if $\lambda > \lambda_c$, and Bazza has a winning strategy if $0 < \lambda < \lambda_c$. If $\lambda_c$ can be written in the form $\frac{1}{\sqrt{m}}$ for some integer $m$, what is the value of $m$?

Budget: 900.00 seconds | Deadline: 1776603663.20

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1            17341             1              0    0.840       2
1        4            19075             5              0    0.800       2
2        3            22873             7              0    0.740       2
3        7            27261             4              0    0.766       2

   Answer  Votes  Score
0       2      4  5.097

Final Answer: 2

>>> Expected: 2 | Predicted: 2 | Correct: True


--- Solving Problem 24/50: tmo_2025_21 ---

Problem: The inscribed circle of a right-angled triangle $ABC$ with $\angle B = 90^\circ$ is tangent to the sides $AB$ and $AC$ at points $D$ and $E$, respectively. Let $F$ be the intersection point of the lines $ED$ and $BC$. If $|FD| = 25$ and $|DE| = 24$, what is $|AE|$?

Budget: 900.00 seconds | Deadline: 1776603933.03

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1             5132            13              1    0.570      20
1        4             5213            13              1    0.630      20
2        6             6601             0              0    0.628      20
3        3             8899             9              0    0.751      20

   Answer  Votes  Score
0      20      4  6.265

Final Answer: 20

>>> Expected: 20 | Predicted: 20 | Correct: True


--- Solving Problem 25/50: imo_2025_01_mod ---

Problem: A line in the plane is called sunny if it is not parallel to any of the $x$-axis, the $y$-axis, and the line $x + y = 0$. Let $n \ge 3$ be a given integer. Determine the sum of all possible nonnegative integers $k$ such that there exist $n$ distinct lines in the plane satisfying both of the following: for all positive integers $a$ and $b$ with $a + b \le n + 1$, the point $(a, b)$ is on at least one of the lines; and exactly $k$ of the $n$ lines are sunny.

Budget: 900.00 seconds | Deadline: 1776604015.38

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1            25841            14              3    0.745       4
1        6            30337            11              8    0.797       4
2        2            51488            28              6    0.722       4
3        3            52637            30              8    0.694       4

   Answer  Votes  Score
0       4      4  5.424

Final Answer: 4

>>> Expected: 4 | Predicted: 4 | Correct: True


--- Solving Problem 26/50: tmo_2025_22 ---

Problem: Let $f(n)$ be the greatest odd divisor of a positive integer $n$. What is the sum $f(25) + f(26) + f(27) + \dots + f(200)$?

Budget: 900.00 seconds | Deadline: 1776604655.58

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             1571             3              0    0.527   13150
1        3             1964             3              0    0.588   13150
2        8             2320             8              0    0.600   13150
3        7             2745             5              0    0.629   13150

   Answer  Votes  Score
0   13150      4  6.854

Final Answer: 13150

>>> Expected: 13150 | Predicted: 13150 | Correct: True


--- Solving Problem 27/50: tmo_2025_23 ---

Problem: If positive real numbers $x$, $y$, and $z$ satisfy the system of equations
\begin{equation*}
\begin{aligned}
\frac{y^2}{z} + \frac{zx+x^2}{2y+z} &= 2x \\\\
\frac{x^2}{z} + \frac{zy+2y^2}{x+z} &= 9y \\\\
\frac{y^2}{x} + \frac{x^2}{y} &= 9z
\end{aligned}
\end{equation*}
what is the value of $\frac{y}{x} + \frac{z}{y} + \frac{x}{z}$?

Budget: 900.00 seconds | Deadline: 1776604682.13

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1             3369             6              0    0.549       5
1        6             3484             6              0    0.431       5
2        2             3526             9              0    0.604       5
3        4             3650             8              0    0.428       5

   Answer  Votes  Score
0       5      4  8.135

Final Answer: 5

>>> Expected: 5 | Predicted: 5 | Correct: True


--- Solving Problem 28/50: reference_10 ---

Problem: Let $n \ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define
\begin{equation*}
g(c) = \frac{1}{2025!} \left\lfloor \frac{2025! f(M+c)}{M} \right\rfloor.
\end{equation*}
We can write
\begin{equation*}
g(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \frac{p}{q}
\end{equation*}
where $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776604719.66

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2            32975            81              2    0.709   98745
1        3            37497            74              5    0.733   77463
2        6            40610            52              1    0.727    8687
3        8            43134            78              4    0.697    8687
4        1            47301            51              7    0.701    <NA>
5        4            54942            43              2    0.726   54680
6        5            58884            64              1    0.695    8687
7        7            63607            26              0    0.717    <NA>

   Answer  Votes  Score
0    8687      3  4.250
1   98745      1  1.410
2   54680      1  1.378
3   77463      1  1.364

Final Answer: 8687

>>> Expected: 8687 | Predicted: 8687 | Correct: True


--- Solving Problem 29/50: tmo_2025_26 ---

Problem: Let $p$ be a prime number, and let $f(p)$ be the number of integers $x$ that satisfy the condition $x + p^2 \mid x^3 + p^4$. For how many of the numbers $m \in \{150, 160, 170, 180, 190\}$ does there exist a prime number $p$ such that $f(p) = m$?

Budget: 900.00 seconds | Deadline: 1776605378.26

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             8450             3              0    0.700       2
1        2            11116             6              1    0.646       2
2        8            11960             7              2    0.645       2
3        7            16187            10              1    0.610       2

   Answer  Votes  Score
0       2      4  6.166

Final Answer: 2

>>> Expected: 2 | Predicted: 2 | Correct: True


--- Solving Problem 30/50: tmo_2025_27 ---

Problem: Initially, there is 1 liter of a homogeneous mixture in a blue jar consisting of $99\%$ pomegranate juice and $1\%$ orange juice, and 2 liters of a homogeneous mixture in a green jar consisting of $1\%$ pomegranate juice and $99\%$ orange juice. In each step, first, 1 liter of mixture is transferred from the green jar to the blue jar and mixed until it is homogeneous. Then, 1 liter of mixture is transferred from the blue jar back to the green jar and mixed until it is homogeneous. After at least how many steps will the absolute difference between the percentage of pomegranate juice in the blue jar and the percentage of pomegranate juice in the green jar be strictly less than $0.1\%$?

Budget: 900.00 seconds | Deadline: 1776605539.28

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             2601             0              0    0.603       5
1        8             2601             0              0    0.577       5
2        5             3280             4              0    0.454       5
3        3             3600             3              0    0.549       5

   Answer  Votes  Score
0       5      4  7.417

Final Answer: 5

>>> Expected: 5 | Predicted: 5 | Correct: True


--- Solving Problem 31/50: reference_10 ---

Problem: Let $n \ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define
\begin{equation*}
g(c) = \frac{1}{2025!} \left\lfloor \frac{2025! f(M+c)}{M} \right\rfloor.
\end{equation*}
We can write
\begin{equation*}
g(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \frac{p}{q}
\end{equation*}
where $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776605574.21

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5            40026           103              4    0.727    8687
1        3            44111            21              0    0.765    <NA>
2        2            46585            59              1    0.689     398
3        8            47605            73              5    0.728   41754
4        7            50768            43              1    0.730    <NA>
5        6            51317            75              4    0.688   41754
6        1            61257            42              3    0.713    <NA>
7        4            61636            37              5    0.715    <NA>

   Answer  Votes  Score
0   41754      2  2.826
1     398      1  1.450
2    8687      1  1.376

Final Answer: 41754

>>> Expected: 8687 | Predicted: 41754 | Correct: False


--- Solving Problem 32/50: tmo_2025_28 ---

Problem: 25 points are marked on a circle with a circumference of 25 units such that these points are the vertices of a regular 25-gon, and $k$ of these points are colored red. If, regardless of how this coloring is done, there are always two red points such that the length of the shorter arc between them is 5 units, what is the minimum possible value of $k$?

Budget: 900.00 seconds | Deadline: 1776606280.74

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8             2379             1              0    0.834      11
1        1             2401             0              0    0.880      11
2        5             2401             0              0    0.938      11
3        2             2692             2              0    0.846      11

   Answer  Votes  Score
0      11      4  4.585

Final Answer: 11

>>> Expected: 11 | Predicted: 11 | Correct: True


--- Solving Problem 33/50: tmo_2025_30 ---

Problem: How many integers $n$ are there such that the expression $n^4 - 5n^3 + 26n^2 - 41n + 19$ is equal to an integer power of a prime number?

Budget: 900.00 seconds | Deadline: 1776606305.93

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             6338             3              0    0.698       3
1        8             7185             3              0    0.684       3
2        2             6734             7              0    0.751       3
3        1             8030             5              1    0.698       3

   Answer  Votes  Score
0       3      4  5.658

Final Answer: 3

>>> Expected: 3 | Predicted: 3 | Correct: True


--- Solving Problem 34/50: tmo_2025_32 ---

Problem: A $1 \times N$ chessboard, with initially no unit squares colored, is drawn on a board. Two players, $A$ and $B$, play a game by taking turns making moves, with player $A$ starting the game. In their turn, player $A$ colors an uncolored unit square red, and player $B$ colors an uncolored unit square blue in their turn. Neither player is allowed to make a move such that two unit squares sharing a common edge have the same color. The player who cannot make a move loses the game. If the game is played exactly once for each of the values $N \in \{2023, 2024, 2025, 2026, 2027\}$, how many of these games can player $A$ guarantee to win?

Budget: 900.00 seconds | Deadline: 1776606387.58

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2            14147             7              2    0.901       0
1        1            18287             7              2    0.934       0
2        5            20288            14              3    0.916       0
3        8            22285             4              2    0.996       0

   Answer  Votes  Score
0       0      4  4.277

Final Answer: 0

>>> Expected: 0 | Predicted: 0 | Correct: True


--- Solving Problem 35/50: reference_01 ---

Problem: Alice and Bob are each holding some integer number of sweets. Alice says to Bob: "If we each added the number of sweets we're holding to our (positive integer) age, my answer would be double yours. If we took the product, then my answer would be four times yours." Bob replies: "Why don't you give me five of your sweets because then both our sum and product would be equal." What is the product of Alice and Bob's ages?

Budget: 900.00 seconds | Deadline: 1776606618.37

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             1625             1              0    0.621      50
1        1             2505             1              0    0.626      50
2        4             2674             1              0    0.573      50
3        8             2042             4              1    0.464      50

   Answer  Votes  Score
0      50      4  7.106

Final Answer: 50

>>> Expected: 50 | Predicted: 50 | Correct: True


--- Solving Problem 36/50: reference_02 ---

Problem: A $500 \times 500$ square is divided into $k$ rectangles, each having integer side lengths. Given that no two of these rectangles have the same perimeter, the largest possible value of $k$ is $\mathcal{K}$. What is the remainder when $\mathcal{K}$ is divided by $10^5$?

Budget: 900.00 seconds | Deadline: 1776606647.86

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3            16182             4              0    0.913     520
1        4            20245             7              0    0.985     520
2        6            33588            14              0    0.874     520
3        5            35293            20              1    0.889     520

   Answer  Votes  Score
0     520      4  4.379

Final Answer: 520

>>> Expected: 520 | Predicted: 520 | Correct: True


--- Solving Problem 37/50: reference_03 ---

Problem: Let $ABC$ be an acute-angled triangle with integer side lengths and $AB < AC$. Points $D$ and $E$ lie on segments $BC$ and $AC$, respectively, such that $AD = AE = AB$. Line $DE$ intersects $AB$ at $X$. Circles $BXD$ and $CED$ intersect for the second time at $Y \neq D$. Suppose that $Y$ lies on line $AD$. There is a unique such triangle with minimal perimeter. This triangle has side lengths $a = BC$, $b = CA$, and $c = AB$. Find the remainder when $abc$ is divided by $10^5$.

Budget: 900.00 seconds | Deadline: 1776607014.74

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2            12540            20              3    0.583     336
1        8            15109             9              0    0.719     336
2        1            15017            16              1    0.620     336
3        7            16457             7              0    0.591     336

   Answer  Votes  Score
0     336      4   6.41

Final Answer: 336

>>> Expected: 336 | Predicted: 336 | Correct: True


--- Solving Problem 38/50: reference_10 ---

Problem: Let $n \ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define
\begin{equation*}
g(c) = \frac{1}{2025!} \left\lfloor \frac{2025! f(M+c)}{M} \right\rfloor.
\end{equation*}
We can write
\begin{equation*}
g(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \frac{p}{q}
\end{equation*}
where $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776607176.44

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2            37984            91              2    0.712   40958
1        3            40590            39              3    0.700   41754
2        5            43733            32              1    0.711    <NA>
3        7            43469            55              6    0.742   98744
4        1            46906            63              8    0.718   31329
5        6            48644            59              0    0.737    8687
6        4            50579            46              3    0.731   96985
7        8            52319            34              3    0.764      17

   Answer  Votes  Score
0   41754      1  1.429
1   40958      1  1.404
2   31329      1  1.392
3   96985      1  1.368
4    8687      1  1.357
5   98744      1  1.348
6      17      1  1.308

Final Answer: 41754

>>> Expected: 8687 | Predicted: 41754 | Correct: False


--- Solving Problem 39/50: reference_04 ---

Problem: Let $f \colon \mathbb{Z}_{\ge 1} \to \mathbb{Z}_{\ge 1}$ be a function such that for all positive integers $m$ and $n$,
\begin{equation*}
f(m) + f(n) = f(m + n + mn).
\end{equation*}
Across all functions $f$ such that $f(n) \le 1000$ for all $n \le 1000$, how many different values can $f(2024)$ take?

Budget: 900.00 seconds | Deadline: 1776607772.34

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             8805             4              1    0.782     580
1        5            11268             7              0    0.823     580
2        4            10574            10              0    0.825     580
3        2            10380            13              1    0.789     580

   Answer  Votes  Score
0     580      4  4.974

Final Answer: 580

>>> Expected: 580 | Predicted: 580 | Correct: True


--- Solving Problem 40/50: reference_05 ---

Problem: A tournament is held with $2^{20}$ runners each of which has a different running speed. In each race, two runners compete against each other with the faster runner always winning the race. The competition consists of 20 rounds with each runner starting with a score of 0. In each round, the runners are paired in such a way that in each pair, both runners have the same score at the beginning of the round. The winner of each race in the $i^{\text{th}}$ round receives $2^{20-i}$ points and the loser gets no points.

At the end of the tournament, we rank the competitors according to their scores. Let $N$ denote the number of possible orderings of the competitors at the end of the tournament. Let $k$ be the largest positive integer such that $10^k$ divides $N$. What is the remainder when $k$ is divided by $10^5$?

Budget: 900.00 seconds | Deadline: 1776607886.98

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            10489             6              0    0.879   21818
1        2            13441            12              1    0.820   21818
2        4            14179            11              0    0.876   21818
3        8            13859            14              2    0.795   21818

   Answer  Votes  Score
0   21818      4  4.756

Final Answer: 21818

>>> Expected: 21818 | Predicted: 21818 | Correct: True


--- Solving Problem 41/50: imo_2025_01_mod ---

Problem: A line in the plane is called sunny if it is not parallel to any of the $x$-axis, the $y$-axis, and the line $x + y = 0$. Let $n \ge 3$ be a given integer. Determine the sum of all possible nonnegative integers $k$ such that there exist $n$ distinct lines in the plane satisfying both of the following: for all positive integers $a$ and $b$ with $a + b \le n + 1$, the point $(a, b)$ is on at least one of the lines; and exactly $k$ of the $n$ lines are sunny.

Budget: 900.00 seconds | Deadline: 1776608032.10

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3            27105             8              2    0.805       1
1        2            39472            17              2    0.813       4
2        1            39575            21              6    0.768       4
3        8            41697            47              9    0.693       4
4        5            45239            52             11    0.656       4

   Answer  Votes  Score
0       4      4  5.499
1       1      1  1.243

Final Answer: 4

>>> Expected: 4 | Predicted: 4 | Correct: True


--- Solving Problem 42/50: reference_06 ---

Problem: Define a function $f \colon \mathbb{Z}_{\ge 1} \to \mathbb{Z}_{\ge 1}$ by
\begin{equation*}
f(n) = \sum_{i=1}^n \sum_{j=1}^n j^{1024} \left\lfloor \frac{1}{j} + \frac{n-i}{n} \right\rfloor.
\end{equation*}
Let $M = 2 \cdot 3 \cdot 5 \cdot 7 \cdot 11 \cdot 13$ and let $N = f(M^{15}) - f(M^{15} - 1)$. Let $k$ be the largest non-negative integer such that $2^k$ divides $N$. What is the remainder when $2^k$ is divided by $5^7$?

Budget: 900.00 seconds | Deadline: 1776608588.19

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             4186             4              0    0.548   32951
1        6             4390             3              0    0.578   32951
2        2             5835             3              0    0.609   32951
3        1             6180             7              0    0.533   32951

   Answer  Votes  Score
0   32951      4  7.075

Final Answer: 32951

>>> Expected: 32951 | Predicted: 32951 | Correct: True


--- Solving Problem 43/50: reference_07 ---

Problem: Let $ABC$ be a triangle with $AB \neq AC$, circumcircle $\Omega$, and incircle $\omega$. Let the contact points of $\omega$ with $BC$, $CA$, and $AB$ be $D$, $E$, and $F$, respectively. Let the circumcircle of $AFE$ meet $\Omega$ at $K$ and let the reflection of $K$ in $EF$ be $K'$. Let $N$ denote the foot of the perpendicular from $D$ to $EF$. The circle tangent to line $BN$ and passing through $B$ and $K$ intersects $BC$ again at $T \neq B$.

Let sequence $(F_n)_{n \ge 0}$ be defined by $F_0 = 0$, $F_1 = 1$ and for $n \ge 2$, $F_n = F_{n-1} + F_{n-2}$. Call $ABC$ $n$\emph{-tastic} if $BD = F_n$, $CD = F_{n+1}$, and $KNK'B$ is cyclic. Across all $n$-tastic triangles, let $a_n$ denote the maximum possible value of $\frac{CT \cdot NB}{BT \cdot NE}$. Let $\alpha$ denote the smallest real number such that for all sufficiently large $n$, $a_{2n} < \alpha$. Given that $\alpha = p + \sqrt{q}$ for rationals $p$ and $q$, what is the remainder when $\left\lfloor p^{q^p} \right\rfloor$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776608648.59

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6            16419            22              3    0.624   57447
1        8            19239            33              2    0.550   57447
2        3            20930            28              5    0.688   57447
3        1            20763            37              9    0.556   57447

   Answer  Votes  Score
0   57447      4  6.673

Final Answer: 57447

>>> Expected: 57447 | Predicted: 57447 | Correct: True


--- Solving Problem 44/50: reference_08 ---

Problem: On a blackboard, Ken starts off by writing a positive integer $n$ and then applies the following move until he first reaches $1$. Given that the number on the board is $m$, he chooses a base $b$, where $2 \le b \le m$, and considers the unique base-$b$ representation of $m$,
\begin{equation*}
m = \sum_{k=0}^\infty a_k \cdot b^k
\end{equation*}
where $a_k$ are non-negative integers and $0 \le a_k < b$ for each $k$. Ken then erases $m$ on the blackboard and replaces it with $\sum_{k=0}^\infty a_k$.

Across all choices of $1 \le n \le 10^{10^5}$, the largest possible number of moves Ken could make is $M$. What is the remainder when $M$ is divided by $10^5$?

Budget: 900.00 seconds | Deadline: 1776608909.35

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             8715             9              0    0.698   32193
1        2             8832             8              0    0.823   32193
2        6            11323            24              0    0.716   32193
3        7            13657            10              0    0.661   32193

   Answer  Votes  Score
0   32193      4  5.556

Final Answer: 32193

>>> Expected: 32193 | Predicted: 32193 | Correct: True


--- Solving Problem 45/50: tmo_2025_12 ---

Problem: Let $k$ be a positive integer. One of the numbers $1, 2, \dots, k$ is written in each unit square of a $4 \times 4$ chessboard. If for every pair $(m,n)$ satisfying $1 \le m < n \le k$, there exists a row or a column containing both $m$ and $n$, what is the maximum possible value of $k$?

Budget: 900.00 seconds | Deadline: 1776609045.58

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            13227             5              1    0.871       8
1        1            20021             9              2    0.845       8
2        5            23907             6              0    0.847       8
3        2            32075            11              0    0.824       6
4        8            38556            16              4    0.781       8

   Answer  Votes  Score
0       8      4  4.792
1       6      1  1.214

Final Answer: 8

>>> Expected: 8 | Predicted: 8 | Correct: True


--- Solving Problem 46/50: reference_09 ---

Problem: Let $\mathcal{F}$ be the set of functions $\alpha \colon \mathbb{Z} \to \mathbb{Z}$ for which there are only finitely many $n \in \mathbb{Z}$ such that $\alpha(n) \neq 0$.

For two functions $\alpha$ and $\beta$ in $\mathcal{F}$, define their product $\alpha \star \beta$ to be $\sum_{n \in \mathbb{Z}} \alpha(n) \cdot \beta(n)$. Also, for $n \in \mathbb{Z}$, define a shift operator $S_n \colon \mathcal{F} \to \mathcal{F}$ by $S_n(\alpha)(t) = \alpha(t+n)$ for all $t \in \mathbb{Z}$.

A function $\alpha \in \mathcal{F}$ is called \emph{shifty} if
\begin{itemize}
\item $\alpha(m) = 0$ for all integers $m < 0$ and $m > 8$ and
\item There exists $\beta \in \mathcal{F}$ and integers $k \neq l$ such that for all $n \in \mathbb{Z}$
\begin{equation*}
S_n(\alpha) \star \beta = \begin{cases} 1 & n \in \{k,l\} \\\\ 0 & n \notin \{k,l\} \end{cases}.
\end{equation*}
\end{itemize}
How many shifty functions are there in $\mathcal{F}$?

Budget: 900.00 seconds | Deadline: 1776609444.79

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2            14666             4              2    0.814      90
1        5            18015            15              1    0.741      44
2        4            20397            19              2    0.759     160
3        3            22558            14              0    0.801     160
4        7            23237            21              5    0.772     160
5        8            24647            34              3    0.752     160

   Answer  Votes  Score
0     160      4  5.191
1      44      1  1.350
2      90      1  1.229

Final Answer: 160

>>> Expected: 160 | Predicted: 160 | Correct: True


--- Solving Problem 47/50: reference_10 ---

Problem: Let $n \ge 6$ be a positive integer. We call a positive integer $n$-Norwegian if it has three distinct positive divisors whose sum is equal to $n$. Let $f(n)$ denote the smallest $n$-Norwegian positive integer. Let $M = 3^{2025!}$ and for a non-negative integer $c$ define
\begin{equation*}
g(c) = \frac{1}{2025!} \left\lfloor \frac{2025! f(M+c)}{M} \right\rfloor.
\end{equation*}
We can write
\begin{equation*}
g(0) + g(4M) + g(1848374) + g(10162574) + g(265710644) + g(44636594) = \frac{p}{q}
\end{equation*}
where $p$ and $q$ are coprime positive integers. What is the remainder when $p+q$ is divided by $99991$?

Budget: 900.00 seconds | Deadline: 1776609693.25

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7            36868            55              1    0.697   41754
1        3            46294            71              5    0.723    8687
2        6            49596            50              4    0.721   54680
3        4            49382            53              4    0.733     189
4        5            51928            49              0    0.695   21371
5        1            55130            27              1    0.704      23
6        2            54292            41              8    0.747    5534
7        8            61734            45              8    0.726    <NA>

   Answer  Votes  Score
0   21371      1  1.438
1   41754      1  1.435
2      23      1  1.420
3   54680      1  1.387
4    8687      1  1.384
5     189      1  1.364
6    5534      1  1.339

Final Answer: 21371

>>> Expected: 8687 | Predicted: 21371 | Correct: False


--- Solving Problem 48/50: imo_2025_01_mod ---

Problem: A line in the plane is called sunny if it is not parallel to any of the $x$-axis, the $y$-axis, and the line $x + y = 0$. Let $n \ge 3$ be a given integer. Determine the sum of all possible nonnegative integers $k$ such that there exist $n$ distinct lines in the plane satisfying both of the following: for all positive integers $a$ and $b$ with $a + b \le n + 1$, the point $(a, b)$ is on at least one of the lines; and exactly $k$ of the $n$ lines are sunny.

Budget: 900.00 seconds | Deadline: 1776610392.74

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1            40073            23              6    0.797       4
1        4            45008            60              8    0.624       4
2        5            49935            37              5    0.746       4
3        7            49375            53             12    0.689       4

   Answer  Votes  Score
0       4      4   5.65

Final Answer: 4

>>> Expected: 4 | Predicted: 4 | Correct: True


--- Solving Problem 49/50: imo_2025_03 ---

Problem: Let $\mathbb{N}$ denote the set of positive integers. A function $f \colon \mathbb{N} \to \mathbb{N}$ is said to be bonza if $f(a)$ divides $b^a - f(b)^{f(a)}$ for all positive integers $a$ and $b$. Determine the smallest real constant $c$ such that $f(n) \le cn$ for all bonza functions $f$ and all positive integers $n$.

Budget: 900.00 seconds | Deadline: 1776611035.75

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5            27303            44              1    0.636       4
1        4            28968            37              1    0.682       4
2        2            36301            51              0    0.659    <NA>
3        1            40008            45              3    0.677       4
4        7            40951            40              1    0.677       4

   Answer  Votes  Score
0       4      4  5.992

Final Answer: 4

>>> Expected: 4 | Predicted: 4 | Correct: True


--- Solving Problem 50/50: imo_2025_05_mod ---

Problem: Alice and Bazza are playing a two-player game whose rules depend on a positive real number $\lambda$ which is known to both players. On the $n^{\text{th}}$ turn of the game (starting with $n = 1$) the following happens: If $n$ is odd, Alice chooses a nonnegative real number $x_n$ such that $x_1 + x_2 + \dots + x_n \le \lambda n$. If $n$ is even, Bazza chooses a nonnegative real number $x_n$ such that $x_1^2 + x_2^2 + \dots + x_n^2 \le n$. If a player cannot choose a suitable number $x_n$, the game ends and the other player wins. If the game goes on forever, neither player wins. All chosen numbers are known to both players. There is a critical threshold $\lambda_c$ such that Alice has a winning strategy if $\lambda > \lambda_c$, and Bazza has a winning strategy if $0 < \lambda < \lambda_c$. If $\lambda_c$ can be written in the form $\frac{1}{\sqrt{m}}$ for some integer $m$, what is the value of $m$?

Budget: 900.00 seconds | Deadline: 1776611485.39

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5            30389            14              1    0.816       2
1        4            31543             7              0    0.844       2
2        8            36801             0              0    0.784       2
3        1            38575             2              0    0.843       2

   Answer  Votes  Score
0       2      4  4.871

Final Answer: 2

>>> Expected: 2 | Predicted: 2 | Correct: True


==================================================
=== FINAL EXPERIMENT SUMMARY ===
==================================================

                 id  expected  predicted  correct
0       tmo_2025_01         2          2     True
1       tmo_2025_12         8          8     True
2       tmo_2025_02       179        179     True
3      reference_10      8687       8687     True
4   imo_2025_01_mod         4          4     True
5       tmo_2025_03        48         48     True
6       tmo_2025_04      3120       3120     True
7      reference_10      8687       8687     True
8       tmo_2025_05        20         20     True
9       tmo_2025_06         4          4     True
10  imo_2025_05_mod         2          2     True
11      tmo_2025_07        11         11     True
12      tmo_2025_10       512        512     True
13      tmo_2025_12         8          8     True
14     reference_10      8687      42534    False
15      tmo_2025_13         4          4     True
16      tmo_2025_14       945        945     True
17      tmo_2025_12         8          8     True
18      tmo_2025_15      2026       2026     True
19      tmo_2025_19         2          2     True
20     reference_10      8687      41754    False
21      tmo_2025_20         3          3     True
22  imo_2025_05_mod         2          2     True
23      tmo_2025_21        20         20     True
24  imo_2025_01_mod         4          4     True
25      tmo_2025_22     13150      13150     True
26      tmo_2025_23         5          5     True
27     reference_10      8687       8687     True
28      tmo_2025_26         2          2     True
29      tmo_2025_27         5          5     True
30     reference_10      8687      41754    False
31      tmo_2025_28        11         11     True
32      tmo_2025_30         3          3     True
33      tmo_2025_32         0          0     True
34     reference_01        50         50     True
35     reference_02       520        520     True
36     reference_03       336        336     True
37     reference_10      8687      41754    False
38     reference_04       580        580     True
39     reference_05     21818      21818     True
40  imo_2025_01_mod         4          4     True
41     reference_06     32951      32951     True
42     reference_07     57447      57447     True
43     reference_08     32193      32193     True
44      tmo_2025_12         8          8     True
45     reference_09       160        160     True
46     reference_10      8687      21371    False
47  imo_2025_01_mod         4          4     True
48      imo_2025_03         4          4     True
49  imo_2025_05_mod         2          2     True

Overall Accuracy: 90.00% (45/50 correct)